[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.ManageCartableActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.GetTransactionSummaryActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.MoveCartableItemActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#PrepareMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionBasicWorkflow.#PrepareMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionBasicWorkflow.#ReviewMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionBasicWorkflow.#RejectReviewedMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionBasicWorkflow.#ConfirmMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionBasicWorkflow.#ApproveMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#PrepareMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#ReviewMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#RejectReviewedMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#ConfirmMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#ApproveMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#PrepareMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#ReviewMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#RejectReviewedMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#ConfirmMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#ApproveMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#ReviewMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#RejectReviewedMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#ConfirmMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#ApproveMultiple(System.Collections.Generic.IEnumerable`1<System.Int32>,System.String)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.Activities.TrackWorkflowStateActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.Activities.GetTransactionFromDocumentActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Argument is checked using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Req", Scope = "type", Target = "SPPC.Tadbir.Workflow.Workflows.ReqVoucherStateWorkflow", Justification = "Generated code")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.Activities.GetWorkflowMetadataActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Argument is checked using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Service.ConfigSettingsRepository.#SaveWorkflowSettings(SPPC.Tadbir.ViewModel.Settings.WorkflowSettingsViewModel)", Justification = "Argument is checked using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Configuration.WorkflowEditionElementCollection.#Remove(SPPC.Tadbir.Configuration.WorkflowEditionElement)", Justification = "Argument is checked using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Configuration.WorkflowElementCollection.#Remove(SPPC.Tadbir.Configuration.WorkflowElement)", Justification = "Argument is checked using Verify utility class.")]

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

