// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.485
//     Template Version: 1.0
//     Generation Date: 2019-01-09 4:37:25 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using SPPC.Framework.Values;

namespace SPPC.Tadbir.ViewModel.Reporting
{
    /// <summary>
    /// اطلاعات یکی از پارامترهای مورد نیاز برای اجرای گزارش را نگهداری می کند
    /// </summary>
    public partial class ParameterViewModel
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public ParameterViewModel()
        {
            FieldName = String.Empty;
            Operator = String.Empty;
            DataType = String.Empty;
            ControlType = String.Empty;
            CaptionKey = String.Empty;
            DefaultValue = String.Empty;
            MinValue = String.Empty;
            MaxValue = String.Empty;
            DescriptionKey = String.Empty;
        }

        /// <summary>
        /// شناسه دیتابیسی این موجودیت که به صورت خودکار توسط دیتابیس تولید می شود
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// نام فیلد متناظر با پارامتر در مدل نمایشی
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string FieldName { get; set; }

        /// <summary>
        /// کد عملگر مورد استفاده برای اعمال مقدار پارامتر
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(16, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Operator { get; set; }

        /// <summary>
        /// نوع داده ای دات نت برای مقدار پارامتر
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string DataType { get; set; }

        /// <summary>
        /// نوع کنترل واسط کاربری مورد نیاز برای گرفتن مقدار پارامتر
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string ControlType { get; set; }

        /// <summary>
        /// کلید متن چندزبانه برای عنوان پارامتر در فرم پارامترها
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string CaptionKey { get; set; }

        /// <summary>
        /// مقدار پیش فرض برای پارامتر جهت پیشنهاد اولیه به کاربر
        /// </summary>
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string DefaultValue { get; set; }

        /// <summary>
        /// حداقل مقدار مورد قبول برای پارامتر
        /// </summary>
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string MinValue { get; set; }

        /// <summary>
        /// حداکثر مقدار مورد قبول برای پارامتر
        /// </summary>
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string MaxValue { get; set; }

        /// <summary>
        /// کلید متن چندزبانه برای شرح معنی و عملکرد پارامتر در فرم پارامترها
        /// </summary>
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string DescriptionKey { get; set; }
    }
}
