// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 2017-08-03 7:01:06 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using SPPC.Tadbir.Model.Finance;
using FluentNHibernate.Mapping;

namespace SPPC.Tadbir.NHibernate.Mapping
{
    /// <summary>
    /// Defines fluent mappings for the <see cref="FullAccount"/> entity class.
    /// </summary>
    public partial class FullAccountMap : ClassMap<FullAccount>
    {
        /// <summary>
        /// Initializes a new instance of the FullAccountMap class and specifies NHibernate mappings
        /// using Fluent NHibernate API.
        /// </summary>
        public FullAccountMap()
        {
            Schema("Finance");
            Table("FullAccount");
            Id(x => x.Id)
                .Column("FullAccountID")
                .GeneratedBy.Identity();
            Map(x => x.RowGuid, "rowguid")
                .Generated.Insert();
            Map(x => x.ModifiedDate);

            MapReferences();
        }

        private void MapReferences()
        {
            References(x => x.Account)
                .Column("AccountID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Detail)
                .Column("DetailID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.CostCenter)
                .Column("CostCenterID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Project)
                .Column("ProjectID")
                .Cascade.None()
                .Not.LazyLoad();
        }
    }
}
