// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.631
//     Template Version: 1.0
//     Generation Date: 03/29/1398 01:04:04 ب.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
import { environment } from "../../../environments/environment";
export class CostCenterApi {
}
// ccenters
CostCenterApi.EnvironmentCostCenters = environment.BaseUrl + "/ccenters";
// ccenters/lookup
CostCenterApi.EnvironmentCostCentersLookup = environment.BaseUrl + "/ccenters/lookup";
// ccenters/ledger
CostCenterApi.EnvironmentCostCentersLedger = environment.BaseUrl + "/ccenters/ledger";
// ccenters/{ccenterId:min(1)}
CostCenterApi.CostCenter = environment.BaseUrl + "/ccenters/{0}";
// ccenters/{ccenterId:min(1)}/previous
CostCenterApi.PreviousEnvironmentCostCenter = environment.BaseUrl + "/ccenters/{0}/previous";
// ccenters/{ccenterId:min(1)}/next
CostCenterApi.NextEnvironmentCostCenter = environment.BaseUrl + "/ccenters/{0}/next";
// ccenters/{ccenterId:min(1)}/children
CostCenterApi.CostCenterChildren = environment.BaseUrl + "/ccenters/{0}/children";
// ccenters/{ccenterId:int}/children/new
CostCenterApi.EnvironmentNewChildCostCenter = environment.BaseUrl + "/ccenters/{0}/children/new";
// ccenters/fullcode/{parentId}
CostCenterApi.CostCenterFullCode = environment.BaseUrl + "/ccenters/fullcode/{0}";
//# sourceMappingURL=costCenterApi.js.map