// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.952
//     Template Version: 1.0
//     Generation Date: 2020-07-15 1:39:15 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { environment } from "@sppc/env/environment";

export class ProfitLossApi {

    // profit-loss
    public static ProfitLoss = environment.BaseUrl + "/profit-loss";

    // profit-loss/simple
    public static ProfitLossSimple = environment.BaseUrl + "/profit-loss/simple";
}