// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.683
//     Template Version: 1.0
//     Generation Date: 05/19/1398 05:11:50 ب.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { environment } from "@sppc/env/environment";

export class TestBalanceApi {

    // testbal/ledger/2-col
    public static TwoColumnLedgerBalance = environment.BaseUrl + "/testbal/ledger/2-col";

    // testbal/ledger/4-col
    public static FourColumnLedgerBalance = environment.BaseUrl + "/testbal/ledger/4-col";

    // testbal/ledger/6-col
    public static SixColumnLedgerBalance = environment.BaseUrl + "/testbal/ledger/6-col";

    // testbal/ledger/8-col
    public static EightColumnLedgerBalance = environment.BaseUrl + "/testbal/ledger/8-col";

    // testbal/ledger/10-col
    public static TenColumnLedgerBalance = environment.BaseUrl + "/testbal/ledger/10-col";

    // testbal/subsid/2-col
    public static TwoColumnSubsidiaryBalance = environment.BaseUrl + "/testbal/subsid/2-col";

    // testbal/subsid/4-col
    public static FourColumnSubsidiaryBalance = environment.BaseUrl + "/testbal/subsid/4-col";

    // testbal/subsid/6-col
    public static SixColumnSubsidiaryBalance = environment.BaseUrl + "/testbal/subsid/6-col";

    // testbal/subsid/8-col
    public static EightColumnSubsidiaryBalance = environment.BaseUrl + "/testbal/subsid/8-col";

    // testbal/subsid/10-col
    public static TenColumnSubsidiaryBalance = environment.BaseUrl + "/testbal/subsid/10-col";

    // testbal/detail/2-col
    public static TwoColumnDetailBalance = environment.BaseUrl + "/testbal/detail/2-col";

    // testbal/detail/4-col
    public static FourColumnDetailBalance = environment.BaseUrl + "/testbal/detail/4-col";

    // testbal/detail/6-col
    public static SixColumnDetailBalance = environment.BaseUrl + "/testbal/detail/6-col";

    // testbal/detail/8-col
    public static EightColumnDetailBalance = environment.BaseUrl + "/testbal/detail/8-col";

    // testbal/detail/10-col
    public static TenColumnDetailBalance = environment.BaseUrl + "/testbal/detail/10-col";

    // testbal/ledger/{accountId:min(1)}/items/2-col
    public static TwoColumnLedgerItemsBalance = environment.BaseUrl + "/testbal/ledger/{0}/items/2-col";

    // testbal/ledger/{accountId:min(1)}/items/4-col
    public static FourColumnLedgerItemsBalance = environment.BaseUrl + "/testbal/ledger/{0}/items/4-col";

    // testbal/ledger/{accountId:min(1)}/items/6-col
    public static SixColumnLedgerItemsBalance = environment.BaseUrl + "/testbal/ledger/{0}/items/6-col";

    // testbal/ledger/{accountId:min(1)}/items/8-col
    public static EightColumnLedgerItemsBalance = environment.BaseUrl + "/testbal/ledger/{0}/items/8-col";

    // testbal/ledger/{accountId:min(1)}/items/10-col
    public static TenColumnLedgerItemsBalance = environment.BaseUrl + "/testbal/ledger/{0}/items/10-col";

    // testbal/subsid/{accountId:min(1)}/items/2-col
    public static TwoColumnSubsidiaryItemsBalance = environment.BaseUrl + "/testbal/subsid/{0}/items/2-col";

    // testbal/subsid/{accountId:min(1)}/items/4-col
    public static FourColumnSubsidiaryItemsBalance = environment.BaseUrl + "/testbal/subsid/{0}/items/4-col";

    // testbal/subsid/{accountId:min(1)}/items/6-col
    public static SixColumnSubsidiaryItemsBalance = environment.BaseUrl + "/testbal/subsid/{0}/items/6-col";

    // testbal/subsid/{accountId:min(1)}/items/8-col
    public static EightColumnSubsidiaryItemsBalance = environment.BaseUrl + "/testbal/subsid/{0}/items/8-col";

    // testbal/subsid/{accountId:min(1)}/items/10-col
    public static TenColumnSubsidiaryItemsBalance = environment.BaseUrl + "/testbal/subsid/{0}/items/10-col";

    // testbal/detail/level/{levelId:min(1)}/2-col
    public static TwoColumnDetailLevelBalance = environment.BaseUrl + "/testbal/detail/level/{0}/2-col";

    // testbal/detail/level/{levelId:min(1)}/4-col
    public static FourColumnDetailLevelBalance = environment.BaseUrl + "/testbal/detail/level/{0}/4-col";

    // testbal/detail/level/{levelId:min(1)}/6-col
    public static SixColumnDetailLevelBalance = environment.BaseUrl + "/testbal/detail/level/{0}/6-col";

    // testbal/detail/level/{levelId:min(1)}/8-col
    public static EightColumnDetailLevelBalance = environment.BaseUrl + "/testbal/detail/level/{0}/8-col";

    // testbal/detail/level/{levelId:min(1)}/10-col
    public static TenColumnDetailLevelBalance = environment.BaseUrl + "/testbal/detail/level/{0}/10-col";
}
