
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.2.1596
//     Template Version: 1.0
//     Generation Date: 10/17/2023 11:57:55 AM 
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using SPPC.Tadbir.Model;
using SPPC.Tadbir.Model.Metadata;
using SPPC.Tadbir.Model.Auth;
using SPPC.Tadbir.Model.Config;
using SPPC.Tadbir.Model.Reporting;

namespace SPPC.Tadbir.Persistence.Seeding
{

    internal class PermissionConfiguration : IEntityTypeConfiguration<Permission>
    {
        public void Configure(EntityTypeBuilder<Permission> builder)
        {
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  1 ,    RowGuid =  new Guid("c4da3bc9-758f-450b-89f6-a5201e48311a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  2 ,    RowGuid =  new Guid("89ae24ee-3599-4ab2-a5ad-dd2ebe281bb2") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  3 ,    RowGuid =  new Guid("d8e449a2-4f17-4b67-8501-ee80fe995c77") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  4 ,    RowGuid =  new Guid("df6f3ab8-fe9a-402d-a15c-15b2356daf83") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  5 ,    RowGuid =  new Guid("f51ac955-619d-44cc-8feb-0d0db04b449e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  6 ,    RowGuid =  new Guid("a8d74aa6-eca7-4275-b6e9-24e3fb5e5655") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  7 ,    RowGuid =  new Guid("fcd74839-d35e-4d87-a25c-b8ab1090eab3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  8 ,    RowGuid =  new Guid("ab7e854f-b3ae-43c5-9bc6-eb749ad31c1c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  9 ,    RowGuid =  new Guid("52f4af81-9469-4e7d-95e2-42ea5e30a3de") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  10 ,    RowGuid =  new Guid("b31bad17-15f1-4677-b556-4ea0bcca0876") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  11 ,    RowGuid =  new Guid("d5312bb1-705d-4a1d-8791-bcee0438ae36") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  12 ,    RowGuid =  new Guid("2bf784dd-c337-42d6-a07e-eea6daac6390") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  13 ,    RowGuid =  new Guid("fb4678f7-29d6-4d49-9633-9af823413d21") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  14 ,    RowGuid =  new Guid("965f1d26-b669-4be4-8d25-89e5b6602490") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  15 ,    RowGuid =  new Guid("8d2c29cf-13f5-4354-b658-d336aaf66a55") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  16 ,    RowGuid =  new Guid("2473d3d5-a604-426b-92c6-a9c5f87fbde7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  17 ,    RowGuid =  new Guid("3560f062-168b-4321-93e6-73d3b75def63") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  18 ,    RowGuid =  new Guid("ce6c6cfe-e61b-499d-b3ce-9eb5169c3cb0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  19 ,    RowGuid =  new Guid("77f143e8-8372-4457-b3a8-9a4ae19edd68") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  20 ,    RowGuid =  new Guid("064d7faf-fd2d-4bf2-839f-9ac9ce40f4f4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  21 ,    RowGuid =  new Guid("9ae428b0-2d97-4c5f-b9f6-1b04dfb3ecfe") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  22 ,    RowGuid =  new Guid("4d542bbe-2a90-421e-994e-4da7d6afa798") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  23 ,    RowGuid =  new Guid("b2be323f-d0ce-4151-92f1-b6549482d767") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  24 ,    RowGuid =  new Guid("cd5a3393-6ba8-4b2d-9c9d-425386d3a5ea") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  25 ,    RowGuid =  new Guid("19aa3744-b3d6-4769-93f3-bbeb387d8734") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  26 ,    RowGuid =  new Guid("24412f00-c057-4089-a7ca-82ec2d072de4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  27 ,    RowGuid =  new Guid("ac4b76fb-1dca-448d-bad2-17c0a04997ae") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  28 ,    RowGuid =  new Guid("a078676b-882d-4e8c-a073-8589208a081b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  29 ,    RowGuid =  new Guid("9ec0a92a-6ebd-4958-888e-3e9124f33e45") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  30 ,    RowGuid =  new Guid("d716c6c0-43e1-4851-b930-8d566beb41ac") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  31 ,    RowGuid =  new Guid("8ff8c965-4754-417e-bcaf-be3d40437ebe") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  32 ,    RowGuid =  new Guid("14db8dff-03c1-4553-b567-b8fd4eb7bd99") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  33 ,    RowGuid =  new Guid("56b7747f-4bc0-40cb-aad4-6dc4afba5cd6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  34 ,    RowGuid =  new Guid("831ca4f2-a8a6-440d-963b-cc08a68f6f03") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  35 ,    RowGuid =  new Guid("745f21e5-b684-4231-97a9-ee91fe4d98d1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  5 ,    Name =  "AssignRolesToEntity,FiscalPeriod" ,    Flag =  128 ,    Description =  "" ,    Id =  36 ,    RowGuid =  new Guid("5511c52e-d7fa-4d54-ab23-6855f915a1d7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  37 ,    RowGuid =  new Guid("8de65dfc-6e69-4634-9061-712039ca25a1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  38 ,    RowGuid =  new Guid("d5676c34-de14-4d17-8fd6-14ca83b3d408") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  39 ,    RowGuid =  new Guid("fbdac679-5b3e-4e5a-b176-ba0b9f0d53c4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  40 ,    RowGuid =  new Guid("caf4c9d3-1ef3-4734-9844-1f17844bb10a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  41 ,    RowGuid =  new Guid("27e5c239-201e-4692-b519-cdca4b466acc") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  42 ,    RowGuid =  new Guid("96bcf93d-da2a-40a2-b8d8-37accfde30b6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  43 ,    RowGuid =  new Guid("186c34e1-640a-4cb2-aeef-17a922723bdc") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "ChangeStatus" ,    Flag =  128 ,    Description =  "" ,    Id =  44 ,    RowGuid =  new Guid("0423e770-94f7-4761-a4ca-281af6fbe0ba") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  45 ,    RowGuid =  new Guid("2b590e3e-51cf-4506-9cb0-6459a3e82d4b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Create" ,    Flag =  2 ,    Description =  "" ,    Id =  46 ,    RowGuid =  new Guid("ea2c17ae-e822-4327-97fe-2a9efbee39ed") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Edit" ,    Flag =  4 ,    Description =  "" ,    Id =  47 ,    RowGuid =  new Guid("8134ae62-740f-48e2-8368-5fe0af329306") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Delete" ,    Flag =  8 ,    Description =  "" ,    Id =  48 ,    RowGuid =  new Guid("1bab857d-991d-4689-9087-3b759fc2e547") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Print" ,    Flag =  16 ,    Description =  "" ,    Id =  49 ,    RowGuid =  new Guid("b5fd371a-f3a4-402b-a6f5-60f52717074f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "CreateLine" ,    Flag =  32 ,    Description =  "" ,    Id =  50 ,    RowGuid =  new Guid("d7f335de-99ef-4264-9422-ed34a38eac1a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "EditLine" ,    Flag =  64 ,    Description =  "" ,    Id =  51 ,    RowGuid =  new Guid("193b9b77-8fb2-47cb-9a9e-42d69ee0c874") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "DeleteLine" ,    Flag =  128 ,    Description =  "" ,    Id =  52 ,    RowGuid =  new Guid("4ca3c4de-a59c-439c-b7cb-c86b4a77867c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Check" ,    Flag =  256 ,    Description =  "" ,    Id =  53 ,    RowGuid =  new Guid("1be59b93-e9fe-4cdf-895c-1307ccdc1bc0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "UndoCheck" ,    Flag =  512 ,    Description =  "" ,    Id =  54 ,    RowGuid =  new Guid("509ef076-44bc-4f92-a00a-fc372b14ae30") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Confirm" ,    Flag =  1024 ,    Description =  "" ,    Id =  55 ,    RowGuid =  new Guid("153309e2-c0cd-4b9d-b15e-292b327fea98") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "UndoConfirm" ,    Flag =  2048 ,    Description =  "" ,    Id =  56 ,    RowGuid =  new Guid("1ad16774-b2b1-44f6-af00-b30ddfc3de42") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Approve" ,    Flag =  4096 ,    Description =  "" ,    Id =  57 ,    RowGuid =  new Guid("cb60d7c3-e3c1-4fe6-a5ef-588fcd617bf1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "UndoApprove" ,    Flag =  8192 ,    Description =  "" ,    Id =  58 ,    RowGuid =  new Guid("784959df-89c2-412e-aa17-816e86f938dc") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "Finalize" ,    Flag =  16384 ,    Description =  "" ,    Id =  59 ,    RowGuid =  new Guid("d1f6179a-eca5-4ae6-a620-8b5572f308da") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  7 ,    Name =  "NavigateEntities,Vouchers" ,    Flag =  32768 ,    Description =  "" ,    Id =  60 ,    RowGuid =  new Guid("26a40fc4-1f54-40e2-a664-ea5f99e5bd22") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  61 ,    RowGuid =  new Guid("d2e379de-f5e4-4388-9c51-cc38a37b7cda") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  62 ,    RowGuid =  new Guid("bb7b8799-5b2b-4282-89d3-2e11194e262e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  63 ,    RowGuid =  new Guid("d21fc7a1-a5f9-435c-aab5-8059bf83acaf") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  64 ,    RowGuid =  new Guid("ee68daf1-d44f-408f-9a56-59395ae737c3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "GroupCheck" ,    Flag =  16 ,    Description =  "" ,    Id =  65 ,    RowGuid =  new Guid("7799bbb0-4a16-4849-a9d1-82b6c2d87832") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "GroupUndoCheck" ,    Flag =  32 ,    Description =  "" ,    Id =  66 ,    RowGuid =  new Guid("6125db24-1815-4534-a747-80551a074598") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "GroupConfirm" ,    Flag =  64 ,    Description =  "" ,    Id =  67 ,    RowGuid =  new Guid("7670ef92-6cd4-44e4-a467-f9fe30c2bec0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "GroupUndoConfirm" ,    Flag =  128 ,    Description =  "" ,    Id =  68 ,    RowGuid =  new Guid("81c26bec-f648-44b3-a2a5-0eeb9cb8f5a3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  8 ,    Name =  "GroupFinalize" ,    Flag =  256 ,    Description =  "" ,    Id =  69 ,    RowGuid =  new Guid("718bc15c-c129-4450-9cec-7146862e3edd") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  70 ,    RowGuid =  new Guid("425e98e4-e5d8-4140-a2e6-6f660a11061e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  71 ,    RowGuid =  new Guid("e557b895-f696-42d4-8f01-5d43752708d6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  72 ,    RowGuid =  new Guid("54243311-5fe9-4602-91c0-09d262022556") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  73 ,    RowGuid =  new Guid("64ed3960-4e58-449a-82fd-153eb3c5403c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  74 ,    RowGuid =  new Guid("b535b39f-c756-4864-9ae8-96c074c4940f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  75 ,    RowGuid =  new Guid("6376c3bd-05ee-4d17-a92f-1964c8dfacf2") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  76 ,    RowGuid =  new Guid("cf4392f8-ff39-4240-8c1e-866c21f1e3b5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  9 ,    Name =  "AssignRolesToEntity,Branch" ,    Flag =  128 ,    Description =  "" ,    Id =  77 ,    RowGuid =  new Guid("976d5bec-37fb-4661-9180-b5a07f367689") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  10 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  78 ,    RowGuid =  new Guid("926f9888-c405-4a3d-820d-b15c0da69aae") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  10 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  79 ,    RowGuid =  new Guid("93c05503-67c9-47fe-9602-8b4d181c74f4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  10 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  80 ,    RowGuid =  new Guid("2b7632ec-a3d8-4497-b339-57c32a572299") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  10 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  81 ,    RowGuid =  new Guid("c06962c9-e2d5-4caf-9823-bba28bc9b237") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  82 ,    RowGuid =  new Guid("461a2b5d-dc84-43f1-b5c3-239803a5d7c5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  83 ,    RowGuid =  new Guid("9b53ca2f-99fe-4968-9218-9d880141ec24") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  84 ,    RowGuid =  new Guid("9e61c9e6-db6b-49f2-9dc8-8c871b3d3c50") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  85 ,    RowGuid =  new Guid("ac61bc65-5ba7-4b8e-a1a3-58ef89cdd168") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  86 ,    RowGuid =  new Guid("9be02e55-4bd6-4eff-934c-78deace76100") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  87 ,    RowGuid =  new Guid("5b937d6b-925f-4ee3-a809-a6afea40b5f6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  11 ,    Name =  "AssignRolesToEntity,User" ,    Flag =  64 ,    Description =  "" ,    Id =  88 ,    RowGuid =  new Guid("666ed088-7531-4b03-936a-3e88b975c842") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  89 ,    RowGuid =  new Guid("2943638f-7199-4db8-a516-ea6ca547a9de") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  90 ,    RowGuid =  new Guid("68693f4c-1dbd-4ed2-aab4-0c179852d859") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  91 ,    RowGuid =  new Guid("a39f98a8-4b5a-41cf-9d6d-13ff525ece35") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  92 ,    RowGuid =  new Guid("84430e0a-2a1e-45d9-8cf3-0d93ad1ab0c6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  93 ,    RowGuid =  new Guid("96e89bf8-06ad-4f84-ae85-e47cb9babd5c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  94 ,    RowGuid =  new Guid("1ba15b96-a483-41a9-8fbb-6e8a8ebb2048") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  95 ,    RowGuid =  new Guid("e82b1ab3-191f-408d-a8b8-9991aa48e449") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "AssignEntityToRole,User" ,    Flag =  128 ,    Description =  "" ,    Id =  96 ,    RowGuid =  new Guid("bc3e841b-b27f-4d11-a0b7-417971b70317") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "AssignEntityToRole,Branch" ,    Flag =  256 ,    Description =  "" ,    Id =  97 ,    RowGuid =  new Guid("31ca6628-1378-46e2-a5e5-89b76261462a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  12 ,    Name =  "AssignEntityToRole,FiscalPeriod" ,    Flag =  512 ,    Description =  "" ,    Id =  98 ,    RowGuid =  new Guid("f0218b61-0bdb-48c0-a04d-b913f17a86b2") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  99 ,    RowGuid =  new Guid("a7b8dcfc-31f5-4ca3-bd9a-3af7acb65278") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  100 ,    RowGuid =  new Guid("9b77389b-b1fe-491d-b047-e56502cc8c96") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  101 ,    RowGuid =  new Guid("98ec0578-bb95-411f-8b01-9297891b82a3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  102 ,    RowGuid =  new Guid("221754f5-1d36-43c1-bfbf-12d726b766c3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  103 ,    RowGuid =  new Guid("c8d7c915-2be8-49e9-80e6-20a0958adea8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  104 ,    RowGuid =  new Guid("a799f8de-96f5-4b82-87b9-bf36a815720b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  13 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  105 ,    RowGuid =  new Guid("36ff8fe6-4576-4186-9209-004264636016") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  14 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  106 ,    RowGuid =  new Guid("5520e79d-04c4-4c8b-a833-00d20a984417") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  14 ,    Name =  "Save" ,    Flag =  2 ,    Description =  "" ,    Id =  107 ,    RowGuid =  new Guid("e8c6a7a1-9e05-4dce-b7dd-6ac33ad1c4d0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  15 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  108 ,    RowGuid =  new Guid("9d6ffb91-53d6-4200-bb53-4736e9f30d83") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  15 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  109 ,    RowGuid =  new Guid("cd8a1b87-1dd6-4789-b806-cbda4b3c7101") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  15 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  110 ,    RowGuid =  new Guid("f5344c17-6280-459d-b068-72436f2247af") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  15 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  111 ,    RowGuid =  new Guid("8bc603a9-5727-4157-ac95-df143513bc75") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  15 ,    Name =  "Archive" ,    Flag =  16 ,    Description =  "" ,    Id =  112 ,    RowGuid =  new Guid("0912589b-b122-41cd-b909-7ba666602dc2") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  15 ,    Name =  "ViewArchive" ,    Flag =  32 ,    Description =  "" ,    Id =  113 ,    RowGuid =  new Guid("e6dbd0a5-9bce-428f-bfb0-ee83e8242cd7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  16 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  114 ,    RowGuid =  new Guid("66c133d0-065b-4638-a16b-2203b30d3056") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  16 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  115 ,    RowGuid =  new Guid("6f36ff1f-3f69-4522-8583-1dbe4422368a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  16 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  116 ,    RowGuid =  new Guid("6f186bb4-a637-4756-83b2-f8e5490f7dee") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  16 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  117 ,    RowGuid =  new Guid("18243fa2-8a4e-4202-b998-873b59ab8153") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  16 ,    Name =  "Archive" ,    Flag =  16 ,    Description =  "" ,    Id =  118 ,    RowGuid =  new Guid("3ab9bca6-8503-4c4e-8067-ecb32e8a02b9") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  16 ,    Name =  "ViewArchive" ,    Flag =  32 ,    Description =  "" ,    Id =  119 ,    RowGuid =  new Guid("722f1e08-53aa-4fd3-93f3-6a7d430e5c92") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  17 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  120 ,    RowGuid =  new Guid("62b62899-4315-476d-aed8-b5725d22724e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  17 ,    Name =  "Design" ,    Flag =  2 ,    Description =  "" ,    Id =  121 ,    RowGuid =  new Guid("ae978842-7326-464f-912e-7e3c39c72f32") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  17 ,    Name =  "QuickReportDesign" ,    Flag =  4 ,    Description =  "" ,    Id =  122 ,    RowGuid =  new Guid("29ce5b15-0158-45c5-8319-7c90a7ebbeb5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  18 ,    Name =  "Save" ,    Flag =  1 ,    Description =  "" ,    Id =  123 ,    RowGuid =  new Guid("958c9239-a516-4997-b5d7-026b1b2ed9bf") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  18 ,    Name =  "Delete" ,    Flag =  2 ,    Description =  "" ,    Id =  124 ,    RowGuid =  new Guid("60d3b27b-6461-450e-826e-d1ef62939693") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  18 ,    Name =  "SetDefault" ,    Flag =  4 ,    Description =  "" ,    Id =  125 ,    RowGuid =  new Guid("ad8c9c6b-9d25-409d-803c-36d892fc779b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  19 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  126 ,    RowGuid =  new Guid("0b9ddd1d-cf9d-4a37-afeb-851c9856d49f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  19 ,    Name =  "Save" ,    Flag =  2 ,    Description =  "" ,    Id =  127 ,    RowGuid =  new Guid("1a8892be-0669-47e4-8d52-750a2a650a9b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  20 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  128 ,    RowGuid =  new Guid("112b4152-2232-4bb0-954f-57f37665b895") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  20 ,    Name =  "Save" ,    Flag =  2 ,    Description =  "" ,    Id =  129 ,    RowGuid =  new Guid("287c80a8-539b-449f-9ae2-9d1e1c5375fd") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  21 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  130 ,    RowGuid =  new Guid("8cb5180e-e5b5-4fc4-ba2a-ac9dee17949c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  21 ,    Name =  "Save" ,    Flag =  2 ,    Description =  "" ,    Id =  131 ,    RowGuid =  new Guid("9afc1465-a8ed-4030-8e46-fcf79cf27e44") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  22 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  132 ,    RowGuid =  new Guid("687ed1be-cf0b-414e-8f5c-7dbe724d22cf") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  22 ,    Name =  "Save" ,    Flag =  2 ,    Description =  "" ,    Id =  133 ,    RowGuid =  new Guid("f8f35aaf-592c-4691-8f0c-dc08bbcefbe8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  134 ,    RowGuid =  new Guid("121ccae9-057e-4165-8153-d4bf50f8c177") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  135 ,    RowGuid =  new Guid("ebb3a6b5-c550-4ea5-854c-e5e79d392ac1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  136 ,    RowGuid =  new Guid("40154567-2212-4b58-a02b-8025873283ce") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  137 ,    RowGuid =  new Guid("c02bb8ad-5df6-41bb-9550-34ec6b497e63") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  138 ,    RowGuid =  new Guid("0114462b-cb2c-4ab7-9222-f539a81270ae") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  139 ,    RowGuid =  new Guid("e8e3b0f0-b965-4365-b5a3-18e013af2da7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  23 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  140 ,    RowGuid =  new Guid("a30eedac-5304-41fa-aa0d-c3c1d04f6d64") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  24 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  141 ,    RowGuid =  new Guid("b31eaaf9-26e2-487c-9675-f682738e90ba") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  24 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  142 ,    RowGuid =  new Guid("71571bf8-9076-4e28-91c0-71e1c2a59015") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  24 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  143 ,    RowGuid =  new Guid("0b01521a-f195-4062-8a9e-80f2a7266ce5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  24 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  144 ,    RowGuid =  new Guid("613ba226-1685-451e-854a-a99f99657b47") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  24 ,    Name =  "Mark" ,    Flag =  16 ,    Description =  "" ,    Id =  145 ,    RowGuid =  new Guid("0e51339f-088f-45e3-85d0-f942e24dfab0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  24 ,    Name =  "ViewByBranch" ,    Flag =  32 ,    Description =  "" ,    Id =  146 ,    RowGuid =  new Guid("d78ae23e-bdcf-477c-989d-85427d7cfe30") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  25 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  147 ,    RowGuid =  new Guid("57dcc4d7-1cf0-4c55-a83b-ee60e7d9f857") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  25 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  148 ,    RowGuid =  new Guid("9841d8f3-4323-4281-ba23-e3f6b145a8b8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  25 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  149 ,    RowGuid =  new Guid("afa9ac82-d802-44dc-968e-e19337e0e5a6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  25 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  150 ,    RowGuid =  new Guid("4755b7d8-df8a-4eb6-a1e9-fc0e573ff0fa") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  25 ,    Name =  "Mark" ,    Flag =  16 ,    Description =  "" ,    Id =  151 ,    RowGuid =  new Guid("7f994e2c-0473-4377-9d0f-5636101d7668") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  25 ,    Name =  "ViewByBranch" ,    Flag =  32 ,    Description =  "" ,    Id =  152 ,    RowGuid =  new Guid("c579d646-311f-4981-b788-911f68ddcea4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  26 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  153 ,    RowGuid =  new Guid("532fc719-adfc-4caf-a18a-2877998e625f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  26 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  154 ,    RowGuid =  new Guid("990ccdda-3eed-4478-b8b6-43e1d5867517") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  26 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  155 ,    RowGuid =  new Guid("7f61e963-6929-43a2-ab71-9b7bbc511a18") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  26 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  156 ,    RowGuid =  new Guid("aedeb6f5-a353-4fa5-98a0-a821ed9f96a0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  26 ,    Name =  "ViewByBranch" ,    Flag =  16 ,    Description =  "" ,    Id =  157 ,    RowGuid =  new Guid("63117bc0-673f-4282-a1dd-b9637b71761e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  27 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  158 ,    RowGuid =  new Guid("f762ba3b-f9ba-48e0-aa53-95cd0293a53b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  27 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  159 ,    RowGuid =  new Guid("db3602c6-7871-4285-b54a-a4d4c8042ba1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  27 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  160 ,    RowGuid =  new Guid("42797ec1-da7b-487c-a290-d916a3bd3bab") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  27 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  161 ,    RowGuid =  new Guid("a2662ba0-1414-4302-9813-2744c746d905") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  27 ,    Name =  "Mark" ,    Flag =  16 ,    Description =  "" ,    Id =  162 ,    RowGuid =  new Guid("1cf2cfbe-8c2b-4959-bf0c-fdfeb2bcc55a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  27 ,    Name =  "ViewByBranch" ,    Flag =  32 ,    Description =  "" ,    Id =  163 ,    RowGuid =  new Guid("51cdbdc4-1f6b-428e-b3b5-9c96283ff857") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  28 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  164 ,    RowGuid =  new Guid("cf4f69c8-4cb8-4779-ab5d-f0ff8028348c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  28 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  165 ,    RowGuid =  new Guid("12aac11b-96ed-4aaa-b7f8-717deb480686") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  28 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  166 ,    RowGuid =  new Guid("d1b4fc4f-b059-4b25-84e2-35787fbbf92f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  28 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  167 ,    RowGuid =  new Guid("6d406c9b-a4a3-48d4-8cdc-dfdc3885e5e3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  28 ,    Name =  "ViewByBranch" ,    Flag =  16 ,    Description =  "" ,    Id =  168 ,    RowGuid =  new Guid("f5f0dc3e-a714-4fa2-9e30-d6c44ec1c60c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  29 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  169 ,    RowGuid =  new Guid("0b9694b3-d6db-44cc-8877-d2d179e45372") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  29 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  170 ,    RowGuid =  new Guid("ede29ba3-c8b2-4224-be41-ebedaf3cc515") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  29 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  171 ,    RowGuid =  new Guid("1735eb37-b6b7-496e-b5bf-7047bfeff579") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  29 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  172 ,    RowGuid =  new Guid("179ecb78-e417-405b-b43e-a9d82f169005") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  29 ,    Name =  "ViewByBranch" ,    Flag =  16 ,    Description =  "" ,    Id =  173 ,    RowGuid =  new Guid("156ab79f-c728-4947-8ed8-50ad6d728d32") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  30 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  174 ,    RowGuid =  new Guid("518fc15f-5c76-4542-8353-e3d7d6fc8ff4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  31 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  175 ,    RowGuid =  new Guid("82764f11-2c54-4113-bf62-959e26216630") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  31 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  176 ,    RowGuid =  new Guid("1de80872-bc01-4271-9839-423b030a32f8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  31 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  177 ,    RowGuid =  new Guid("9b26f07d-2377-403e-b7c1-2a6e6441e10e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  31 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  178 ,    RowGuid =  new Guid("78af3bbc-2d2c-4979-904d-ca6f42b1ed90") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  179 ,    RowGuid =  new Guid("c8f9d004-68be-4128-a7f0-a4c2ced5829f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "Create" ,    Flag =  2 ,    Description =  "" ,    Id =  180 ,    RowGuid =  new Guid("53cb05dd-8ce5-496c-9a2b-b429735b6ee3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "Edit" ,    Flag =  4 ,    Description =  "" ,    Id =  181 ,    RowGuid =  new Guid("515a212f-6731-4cf7-b899-b2376d9f3095") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "Delete" ,    Flag =  8 ,    Description =  "" ,    Id =  182 ,    RowGuid =  new Guid("884c6d84-8f1f-4042-a339-f0d8c9a65bfe") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "Print" ,    Flag =  16 ,    Description =  "" ,    Id =  183 ,    RowGuid =  new Guid("b1ef452f-8db8-40d2-842f-54212f8f6ee8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "CreateLine" ,    Flag =  32 ,    Description =  "" ,    Id =  184 ,    RowGuid =  new Guid("c4ba8b19-3ecd-483b-a725-95a578faf4ae") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "EditLine" ,    Flag =  64 ,    Description =  "" ,    Id =  185 ,    RowGuid =  new Guid("73647425-225f-4d30-b019-ae86f56414ff") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "DeleteLine" ,    Flag =  128 ,    Description =  "" ,    Id =  186 ,    RowGuid =  new Guid("3cc81060-eca6-4e42-82dd-539d19e52a63") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "Check" ,    Flag =  256 ,    Description =  "" ,    Id =  187 ,    RowGuid =  new Guid("c6900e98-e522-4297-804d-9fb7644ff95c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "UndoCheck" ,    Flag =  512 ,    Description =  "" ,    Id =  188 ,    RowGuid =  new Guid("dabd79c7-21d5-4b7e-ae1e-36884b29a100") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "NavigateEntities,DraftVouchers" ,    Flag =  1024 ,    Description =  "" ,    Id =  189 ,    RowGuid =  new Guid("8ab33da4-b0cf-4c21-9d7e-3a42695ab41c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  33 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  190 ,    RowGuid =  new Guid("dba156aa-2c66-43b5-a35c-d9ddd6e63b19") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  33 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  191 ,    RowGuid =  new Guid("d5402787-8653-4d24-8e47-83b1a3215b8e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  33 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  192 ,    RowGuid =  new Guid("af148fc8-d573-474d-bc88-4505a3e592de") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  33 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  193 ,    RowGuid =  new Guid("53630016-e77a-4de4-8fe4-d8d8be421979") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  33 ,    Name =  "GroupCheck" ,    Flag =  16 ,    Description =  "" ,    Id =  194 ,    RowGuid =  new Guid("28ceff08-1ae2-45e5-8104-52c9cfbaed9d") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  33 ,    Name =  "GroupUndoCheck" ,    Flag =  32 ,    Description =  "" ,    Id =  195 ,    RowGuid =  new Guid("d4aebfc4-8bb0-441c-9bd7-4cc3dc2f483d") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  32 ,    Name =  "Normalize" ,    Flag =  2048 ,    Description =  "" ,    Id =  196 ,    RowGuid =  new Guid("fc99a87c-8ea1-413f-91f5-3d3af1645697") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  26 ,    Name =  "FilterByRef" ,    Flag =  32 ,    Description =  "" ,    Id =  197 ,    RowGuid =  new Guid("f1734caf-a327-40c8-9936-bd013e9ecebc") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  28 ,    Name =  "FilterByRef" ,    Flag =  32 ,    Description =  "" ,    Id =  198 ,    RowGuid =  new Guid("2efd202c-2989-4140-9d8e-1f1fdc26a615") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  29 ,    Name =  "FilterByRef" ,    Flag =  32 ,    Description =  "" ,    Id =  199 ,    RowGuid =  new Guid("04eb30e4-c94a-4514-87fa-cec6e84f1fd1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  31 ,    Name =  "FilterByRef" ,    Flag =  16 ,    Description =  "" ,    Id =  200 ,    RowGuid =  new Guid("6ea5b253-fbf8-4764-8235-3471697da0d6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  34 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  201 ,    RowGuid =  new Guid("aca3a945-4b07-420e-bb06-562429da1680") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  34 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  202 ,    RowGuid =  new Guid("9b93d89e-8c4a-4140-9574-c197369ca5d0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  34 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  203 ,    RowGuid =  new Guid("6d91b607-abfe-4232-8151-ee0384f95c18") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  34 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  204 ,    RowGuid =  new Guid("50165020-07fa-425a-828c-2e22511b08fe") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  34 ,    Name =  "FilterByRef" ,    Flag =  16 ,    Description =  "" ,    Id =  205 ,    RowGuid =  new Guid("a513f341-c62b-4e16-9973-897006395401") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  35 ,    Name =  "IssueOpeningVoucher" ,    Flag =  1 ,    Description =  "" ,    Id =  206 ,    RowGuid =  new Guid("c8275c44-5f8f-4cf5-83bd-4ab77326b636") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  35 ,    Name =  "IssueClosingTempAccountsVoucher" ,    Flag =  2 ,    Description =  "" ,    Id =  207 ,    RowGuid =  new Guid("ee27b8fc-d60e-4649-8fe5-3afd038d335a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  35 ,    Name =  "IssueClosingVoucher" ,    Flag =  4 ,    Description =  "" ,    Id =  208 ,    RowGuid =  new Guid("7ff551b2-44ea-410b-9c09-9f9fa32904b5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  35 ,    Name =  "UncheckClosingVoucher" ,    Flag =  8 ,    Description =  "" ,    Id =  209 ,    RowGuid =  new Guid("cf44f13d-c6b2-41b4-9cc6-60dc3eef9ca7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  36 ,    Name =  "ManageDashboard" ,    Flag =  1 ,    Description =  "" ,    Id =  210 ,    RowGuid =  new Guid("8b1f3ca2-d810-40a0-bc70-0f7804f2b888") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  36 ,    Name =  "ManageWidgets" ,    Flag =  2 ,    Description =  "" ,    Id =  211 ,    RowGuid =  new Guid("5109b4cd-7380-4a41-8205-8dcb349564f0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  212 ,    RowGuid =  new Guid("bae82aa2-64ee-4b82-b2ca-ae0cc9da72c8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  213 ,    RowGuid =  new Guid("b402dd46-8d1e-4914-a34e-ba42a21b0455") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  214 ,    RowGuid =  new Guid("c15458f0-c7fc-4737-a4b4-0838494c06bb") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "Create" ,    Flag =  8 ,    Description =  "" ,    Id =  215 ,    RowGuid =  new Guid("4a4bed87-19e9-4379-8275-88a7b340ce42") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "Edit" ,    Flag =  16 ,    Description =  "" ,    Id =  216 ,    RowGuid =  new Guid("9eb1546d-1eba-4fef-8b4d-0f7374df9f45") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "Delete" ,    Flag =  32 ,    Description =  "" ,    Id =  217 ,    RowGuid =  new Guid("3a17b1b1-8dda-4e26-b965-4dfeb9bbc328") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "NavigateEntities,CheckBooks" ,    Flag =  64 ,    Description =  "" ,    Id =  218 ,    RowGuid =  new Guid("95912ad0-d9b4-4809-a618-52ab78461af9") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "CreatePages" ,    Flag =  128 ,    Description =  "" ,    Id =  219 ,    RowGuid =  new Guid("71446465-99a5-4e95-8752-6b5013865a99") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "DeletePages" ,    Flag =  256 ,    Description =  "" ,    Id =  220 ,    RowGuid =  new Guid("9972ff27-0486-4e75-8b98-5b72cde0479a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "CancelPage" ,    Flag =  512 ,    Description =  "" ,    Id =  221 ,    RowGuid =  new Guid("273ec146-2891-403d-a27f-1e81b651b51c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "UndoCancelPage" ,    Flag =  1024 ,    Description =  "" ,    Id =  222 ,    RowGuid =  new Guid("6df44bd2-42af-49e3-8807-f40440d562e2") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "ConnectToCheck" ,    Flag =  2048 ,    Description =  "" ,    Id =  223 ,    RowGuid =  new Guid("ab90cbdd-9366-41a4-b237-523549a658ef") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  37 ,    Name =  "DisconnectFromCheck" ,    Flag =  4096 ,    Description =  "" ,    Id =  224 ,    RowGuid =  new Guid("2d58b116-b60f-4593-8c51-c131905f00d4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  225 ,    RowGuid =  new Guid("8d34abf4-07e2-4e1f-a5f0-9d8209d92d6b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  226 ,    RowGuid =  new Guid("fbd4af24-2117-4277-833e-86e1705e306b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  227 ,    RowGuid =  new Guid("a6b7e0ae-a0f4-445d-a1a1-7147602e7aaa") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  228 ,    RowGuid =  new Guid("af472a8d-8264-4ab8-9a0a-b3c5a03ed64a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  229 ,    RowGuid =  new Guid("8f2cf782-cbfc-4e68-a449-20a92fb05df9") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  230 ,    RowGuid =  new Guid("cb0cc9e1-8c58-48e4-8527-c9b1c3ef86f7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  231 ,    RowGuid =  new Guid("f9450b64-1d2c-4af5-ad8f-337e5231144f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "AssignCashRegisterUser" ,    Flag =  128 ,    Description =  "" ,    Id =  232 ,    RowGuid =  new Guid("8e24f310-00cd-416f-8e4f-9d6e3cdc7765") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  39 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  233 ,    RowGuid =  new Guid("a2d7b0e6-89bc-4f5a-a22f-b2d503e65c42") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  39 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  234 ,    RowGuid =  new Guid("b7ad809a-66a3-49f8-aae7-8c24e59ded33") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  39 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  235 ,    RowGuid =  new Guid("fa3adbbe-eb65-4e51-bcff-678765822be1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  39 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  236 ,    RowGuid =  new Guid("3a5bd266-61a0-4b64-bfb0-4d0ce4cb2efc") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  39 ,    Name =  "Archive" ,    Flag =  16 ,    Description =  "" ,    Id =  237 ,    RowGuid =  new Guid("0bc07f5a-d3b4-435b-a2a5-da4fbc26b87f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  39 ,    Name =  "UndoArchive" ,    Flag =  32 ,    Description =  "" ,    Id =  238 ,    RowGuid =  new Guid("2d4f51b4-97a3-4e7f-bfdd-e6bbc3b12cf4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  239 ,    RowGuid =  new Guid("d868408f-4276-4ab6-9893-ec130fbe634a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  240 ,    RowGuid =  new Guid("22fc6ad9-1d05-447d-9fc7-91275b52d209") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  241 ,    RowGuid =  new Guid("864b5f2c-e02d-44bf-bbc3-f28621b35fcd") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  242 ,    RowGuid =  new Guid("43b4170e-5c57-40e5-9597-60df8d8f535d") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  243 ,    RowGuid =  new Guid("a951afdf-4627-4d74-83f3-aa6114f8fe23") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  244 ,    RowGuid =  new Guid("25a466b3-ab64-4f54-b84e-8a30ec3fa456") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  245 ,    RowGuid =  new Guid("aa5b3542-bc43-4781-ad21-47199fbad0f4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  246 ,    RowGuid =  new Guid("40dd48bb-e5e3-4e75-a778-9789ea148733") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Print" ,    Flag =  2 ,    Description =  "" ,    Id =  247 ,    RowGuid =  new Guid("3b8bba6c-ed54-4fd8-b37e-96efc288136f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Create" ,    Flag =  4 ,    Description =  "" ,    Id =  248 ,    RowGuid =  new Guid("106c700d-f285-4f38-b74c-6d19907aae2c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Edit" ,    Flag =  8 ,    Description =  "" ,    Id =  249 ,    RowGuid =  new Guid("e6b7beb0-bf2c-4ddb-accf-dce0810c0ef0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Delete" ,    Flag =  16 ,    Description =  "" ,    Id =  250 ,    RowGuid =  new Guid("be5138ba-fba0-4288-8df5-084f31377d7c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "NavigateEntities,Payments" ,    Flag =  32 ,    Description =  "" ,    Id =  251 ,    RowGuid =  new Guid("45534857-fbe4-4310-83da-17027ef2b242") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Register" ,    Flag =  64 ,    Description =  "" ,    Id =  252 ,    RowGuid =  new Guid("113d7f38-0eaa-45da-9b27-49df26a5fe2a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Confirm" ,    Flag =  128 ,    Description =  "" ,    Id =  253 ,    RowGuid =  new Guid("c3bf023a-309e-43a2-a7e9-3b7d4def8d6a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "UndoConfirm" ,    Flag =  256 ,    Description =  "" ,    Id =  254 ,    RowGuid =  new Guid("dd694e66-4067-4776-93c3-92b83b7454d7") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "Approve" ,    Flag =  512 ,    Description =  "" ,    Id =  255 ,    RowGuid =  new Guid("00da2789-5999-4449-8c91-71f90934d11f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "UndoApprove" ,    Flag =  1024 ,    Description =  "" ,    Id =  256 ,    RowGuid =  new Guid("b4568e82-b243-4d3c-915a-3dbf56520108") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  257 ,    RowGuid =  new Guid("7b2173b5-54ef-4a83-b3aa-9bdbb053dfc5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Print" ,    Flag =  2 ,    Description =  "" ,    Id =  258 ,    RowGuid =  new Guid("88051952-df85-405b-a6d0-f95b1b179e4a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Create" ,    Flag =  4 ,    Description =  "" ,    Id =  259 ,    RowGuid =  new Guid("d7fdae73-f018-4a98-857d-ebe1c1e27331") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Edit" ,    Flag =  8 ,    Description =  "" ,    Id =  260 ,    RowGuid =  new Guid("77df0d67-e974-4ecb-ba02-fd2b5e3d7b76") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Delete" ,    Flag =  16 ,    Description =  "" ,    Id =  261 ,    RowGuid =  new Guid("b35788ae-08c6-4584-a27c-ca11f8092986") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "NavigateEntities,Receipts" ,    Flag =  32 ,    Description =  "" ,    Id =  262 ,    RowGuid =  new Guid("9a1f3364-1ad6-4b87-9861-44860d3fb3e3") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Register" ,    Flag =  64 ,    Description =  "" ,    Id =  263 ,    RowGuid =  new Guid("8ac03e0a-af92-4414-b595-b67dfa34b803") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Confirm" ,    Flag =  128 ,    Description =  "" ,    Id =  264 ,    RowGuid =  new Guid("4521d5cb-85be-4e7d-8531-105901881a0f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "UndoConfirm" ,    Flag =  256 ,    Description =  "" ,    Id =  265 ,    RowGuid =  new Guid("e75cd3f3-e697-4204-b0fc-c528ca657416") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "Approve" ,    Flag =  512 ,    Description =  "" ,    Id =  266 ,    RowGuid =  new Guid("82707f69-96fe-4d84-9cb4-9bc7e3ec41fd") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "UndoApprove" ,    Flag =  1024 ,    Description =  "" ,    Id =  267 ,    RowGuid =  new Guid("2f9f8542-56d8-4e8e-8597-84133788fb9a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Deactivate" ,    Flag =  128 ,    Description =  "Mark an active account as inactive" ,    Id =  268 ,    RowGuid =  new Guid("06252f81-1b8b-4cde-aef0-c1fc8eda7d52") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  1 ,    Name =  "Reactivate" ,    Flag =  256 ,    Description =  "Mark an inactive account as active" ,    Id =  269 ,    RowGuid =  new Guid("d70db79b-0048-4bfc-ab5b-25e765f92f41") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Deactivate" ,    Flag =  128 ,    Description =  "Mark an active detail account as inactive" ,    Id =  270 ,    RowGuid =  new Guid("bf6c51ec-7629-4c29-b37b-d422e9166192") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  2 ,    Name =  "Reactivate" ,    Flag =  256 ,    Description =  "Mark an inactive detail account as active" ,    Id =  271 ,    RowGuid =  new Guid("2397979e-a13c-4b65-af02-807489f103ac") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Deactivate" ,    Flag =  128 ,    Description =  "Mark an active cost center as inactive" ,    Id =  272 ,    RowGuid =  new Guid("022ee6bf-152a-48bd-ab63-ee1d83f59d42") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  3 ,    Name =  "Reactivate" ,    Flag =  256 ,    Description =  "Mark an inactive cost center as active" ,    Id =  273 ,    RowGuid =  new Guid("41f381a8-e690-4c4c-a982-f4a0800a9540") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Deactivate" ,    Flag =  128 ,    Description =  "Mark an active project as inactive" ,    Id =  274 ,    RowGuid =  new Guid("e36da53d-e968-4953-ac3d-badbb6a67827") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  4 ,    Name =  "Reactivate" ,    Flag =  256 ,    Description =  "Mark an inactive project as active" ,    Id =  275 ,    RowGuid =  new Guid("2c12ed12-d34f-4325-997e-096401bf92e5") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Deactivate" ,    Flag =  128 ,    Description =  "Mark an active currency as inactive" ,    Id =  276 ,    RowGuid =  new Guid("491f216c-d76c-4ee1-8182-f7ff6a90e4f8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  6 ,    Name =  "Reactivate" ,    Flag =  256 ,    Description =  "Mark an inactive currency as active" ,    Id =  277 ,    RowGuid =  new Guid("c0f61a08-c3a8-458d-a9f6-e0cd3a240e83") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Deactivate" ,    Flag =  256 ,    Description =  "Mark an active cash register as inactive" ,    Id =  278 ,    RowGuid =  new Guid("47a56d18-924c-4d21-8d50-6de1fd331762") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  38 ,    Name =  "Reactivate" ,    Flag =  512 ,    Description =  "Mark an inactive cash register as active" ,    Id =  279 ,    RowGuid =  new Guid("2d112efb-76ee-492a-829e-3c06dfbbef6e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Deactivate" ,    Flag =  128 ,    Description =  "Mark an active source/application as inactive" ,    Id =  280 ,    RowGuid =  new Guid("d3290892-0413-4c83-8091-fec529523e5a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  40 ,    Name =  "Reactivate" ,    Flag =  256 ,    Description =  "Mark an inactive source/application as active" ,    Id =  281 ,    RowGuid =  new Guid("2c8125a8-20f4-48c3-b28c-883fc864f00e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  41 ,    Name =  "UndoRegister" ,    Flag =  2048 ,    Description =  "" ,    Id =  282 ,    RowGuid =  new Guid("ec1708e7-edbe-4629-9c99-bc4ed759858d") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  42 ,    Name =  "UndoRegister" ,    Flag =  2048 ,    Description =  "" ,    Id =  283 ,    RowGuid =  new Guid("de4a13b8-3b84-44c1-95db-5374d1523746") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  30 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  284 ,    RowGuid =  new Guid("fb8dba57-8150-4c8c-8500-cd84bb48a5ff") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  30 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  285 ,    RowGuid =  new Guid("811e96de-2e5f-4bfd-b9e3-d41860d08a40") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  30 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  286 ,    RowGuid =  new Guid("a6f0d736-0b16-4933-b3dd-585ba10258ee") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  100001 ,    RowGuid =  new Guid("f07f9a76-a8a0-464e-8e68-9fe1f8f414c2") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  100002 ,    RowGuid =  new Guid("ee1ffedc-b422-4877-b6a7-81cce129ad9c") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  100003 ,    RowGuid =  new Guid("ca788041-2acd-466e-846a-84ac9a247055") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  100004 ,    RowGuid =  new Guid("2a006e4b-54bb-48cf-9b3c-6d710918a1bf") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  100005 ,    RowGuid =  new Guid("7c602940-8118-48d1-9ce2-273dc2ce72fb") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  100006 ,    RowGuid =  new Guid("50b40005-5c3a-4102-a953-da5729350f68") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100001 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  100007 ,    RowGuid =  new Guid("b9810835-8c82-4bf1-be2e-7f5fb20b7756") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  100008 ,    RowGuid =  new Guid("0aedc57f-4911-4bd5-889c-6ccacaea4a47") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  100009 ,    RowGuid =  new Guid("35dbc4b8-3c5b-46ff-b228-1befcdf9d960") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  100010 ,    RowGuid =  new Guid("ad448b2e-df8a-4d8c-ac17-6bed026a6d07") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  100011 ,    RowGuid =  new Guid("db451281-a92d-4c6b-9103-3e5a370843c9") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  100012 ,    RowGuid =  new Guid("bc82729a-911b-45b6-906a-4dfea472deba") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  100013 ,    RowGuid =  new Guid("3e54b2fd-aa6e-4692-8357-808fb1ca3a7b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100002 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  100014 ,    RowGuid =  new Guid("b4fd9ec0-99bd-4733-be15-4023b33b5101") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  100015 ,    RowGuid =  new Guid("e4c1203b-031a-4a6a-8e3d-da82c0bfefe8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  100016 ,    RowGuid =  new Guid("d49d6643-e466-46e0-ba21-52f2405246a9") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  100017 ,    RowGuid =  new Guid("bab17f7d-dc75-4318-a975-fd210cde1506") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  100018 ,    RowGuid =  new Guid("ebce6488-d56f-4def-87ed-38c6fb6600de") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  100019 ,    RowGuid =  new Guid("5ffb80a1-314e-4f74-9733-7b0843f0ad8a") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  100020 ,    RowGuid =  new Guid("4e635add-f272-43ec-be89-b6d7354f3ee1") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100003 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  100021 ,    RowGuid =  new Guid("b591119e-e0ec-46ae-8e6c-0d36fc0a5f19") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  100022 ,    RowGuid =  new Guid("b74bd0c0-7755-4fb5-96a2-8d50e8f48940") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  100023 ,    RowGuid =  new Guid("c696e160-2cbd-4601-8590-8633c4f314d4") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  100024 ,    RowGuid =  new Guid("426aff70-c33c-4d7c-96c0-c5766aa39084") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  100025 ,    RowGuid =  new Guid("6376677e-ae00-43d8-a5f2-edc4cdf78d98") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  100026 ,    RowGuid =  new Guid("31926a8e-f23c-4343-9756-d8139228069e") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  100027 ,    RowGuid =  new Guid("a72dac4f-bed9-43d0-a979-d14f8adc6285") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100004 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  100028 ,    RowGuid =  new Guid("6ac39272-959d-4216-b66d-7bf2436cd98b") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "View" ,    Flag =  1 ,    Description =  "" ,    Id =  100029 ,    RowGuid =  new Guid("c9fe111d-4a65-45f2-88c7-ba9c99432c9f") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "Filter" ,    Flag =  2 ,    Description =  "" ,    Id =  100030 ,    RowGuid =  new Guid("21a15787-4b88-4c46-8d65-8dd0551a27f6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "Print" ,    Flag =  4 ,    Description =  "" ,    Id =  100031 ,    RowGuid =  new Guid("bb1cced0-b530-4ecd-b5a1-a57eba6783e0") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "Export" ,    Flag =  8 ,    Description =  "" ,    Id =  100032 ,    RowGuid =  new Guid("c76ba1f9-ec19-4bda-b4a9-6d9b2dc7430d") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "Create" ,    Flag =  16 ,    Description =  "" ,    Id =  100033 ,    RowGuid =  new Guid("0109d1d5-a24f-4816-ba19-f69370cc34c6") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "Edit" ,    Flag =  32 ,    Description =  "" ,    Id =  100034 ,    RowGuid =  new Guid("f852d506-18d0-49a9-a117-6826e2ec7a09") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
          
            builder.HasData(new Permission {    GroupId =  100005 ,    Name =  "Delete" ,    Flag =  64 ,    Description =  "" ,    Id =  100035 ,    RowGuid =  new Guid("e2422ffa-ce78-40ba-aa71-5ba55a4040f8") ,    ModifiedDate =  DateTime.Parse("10/17/2023 11:57:55 AM")    });
        
        }
    }
}