// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.VouchersController.GetMissingVoucherNumbersAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.VouchersController.GetSystemIssueArticlesAsync(System.String,System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.VouchersController.GetUnbalancedVouchersAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.VouchersController.GetVouchersWithNoArticleAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.SystemIssuesController.GetMissingVoucherNumbersAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.SystemIssuesController.GetSystemIssueArticlesAsync(System.String,System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.SystemIssuesController.GetUnbalancedVouchersAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1008:Opening parenthesis must be spaced correctly", Justification = "Parenthesis is used in tuple short-hand form, not method", Scope = "member", Target = "~M:SPPC.Tadbir.Web.Api.Controllers.SystemIssuesController.GetVouchersWithNoArticleAsync(System.DateTime,System.DateTime)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]