// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.712
//     Template Version: 1.0
//     Generation Date: 9/15/2019 4:08:35 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


export interface TaxCurrency {
    id: number;
    code: number;
    name: string;
}
