// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 2017-08-02 7:42:27 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SPPC.Tadbir.Model.Core
{
    /// <summary>
    /// یکی از وضعیت های ثبتی مربوط به اسناد مالی یا اداری را نشان می دهد
    /// </summary>
    public partial class DocumentStatus : CoreEntity
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس ایجاد می کند.
        /// </summary>
        public DocumentStatus()
        {
            Name = String.Empty;
            ModifiedDate = DateTime.Now;
        }

        /// <summary>
        /// نام وضعیت ثبتی
        /// </summary>
        public virtual string Name { get; set; }
    }
}
