// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.1049
//     Template Version: 1.0
//     Generation Date: 2020-12-29 6:30:02 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using SPPC.Framework.Values;

namespace SPPC.Tadbir.ViewModel.Config
{
    /// <summary>
    /// تنظیمات کلی یکی از فرم های گزارشی قابل سفارشی سازی را نگهداری می کند
    /// </summary>
    public partial class LabelSettingViewModel
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public LabelSettingViewModel()
        {
            ModelType = String.Empty;
            Values = String.Empty;
            DefaultValues = String.Empty;
        }

        /// <summary>
        /// شناسه دیتابیسی این موجودیت که به صورت خودکار توسط دیتابیس تولید می شود
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// نوع کلاس مدل مورد استفاده برای نگهداری مقادیر تنظیمات
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(128, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string ModelType { get; set; }

        /// <summary>
        /// ریز اطلاعات تنظیمات که با فرمت مشخصی ذخیره و بازیابی می شود
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public string Values { get; set; }

        /// <summary>
        /// ریز اطلاعات تنظیمات پیش فرض که با فرمت مشخصی ذخیره و بازیابی می شود
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public string DefaultValues { get; set; }
    }
}
