SET IDENTITY_INSERT [Finance].[AccountCollectionAccount] ON
-- Add bank accounts
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (1, 17, 106, %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (2, 17, 107,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (3, 17, 108,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (4, 17, 109,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (5, 17, 110,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (6, 17, 111,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (7, 17, 112,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (8, 17, 113,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (9, 17, 114,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (10, 17, 115,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (11, 17, 116,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (12, 17, 117,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (13, 17, 118,  %branchId%, %fiscalPeriodId%)

-- Add cashier accounts
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (14, 16, 102,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (15, 16, 103,  %branchId%, %fiscalPeriodId%)

-- Add liquid asset accounts
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (16, 1, 101,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (17, 1, 106,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (18, 1, 119,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (19, 1, 120,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (20, 1, 124,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (21, 1, 126,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (22, 1, 130,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (23, 1, 131,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (24, 1, 135,  %branchId%, %fiscalPeriodId%)

-- Add liquid liability accounts
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (25, 3, 146,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (26, 3, 148,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (27, 3, 150,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (28, 3, 160,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (29, 3, 161,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (30, 3, 162,  %branchId%, %fiscalPeriodId%)
INSERT INTO [Finance].[AccountCollectionAccount] ([AccountCollectionAccountID], [CollectionID], [AccountID], [BranchID], [FiscalPeriodID])
    VALUES (31, 3, 163,  %branchId%, %fiscalPeriodId%)

SET IDENTITY_INSERT [Finance].[AccountCollectionAccount] OFF