// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 2017-08-02 7:42:27 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SPPC.Framework.Domain;
using SPPC.Tadbir.Model.Corporate;

namespace SPPC.Tadbir.Model.Finance
{
    /// <summary>
    /// TODO: Add description...
    /// </summary>
    public partial class DetailAccount : IEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DetailAccount"/> class.
        /// </summary>
        public DetailAccount()
        {
            this.Code = String.Empty;
            this.FullCode = String.Empty;
            this.Name = String.Empty;
            this.ModifiedDate = DateTime.Now;
            InitReferences();
        }

        /// <summary>
        /// Gets or sets the unique identifier for this entity. This property is auto-generated.
        /// </summary>
        public virtual int Id { get; set; }

        /// <summary>
        /// TODO: Add description...
        /// </summary>
        public virtual string Code { get; set; }

        /// <summary>
        /// TODO: Add description...
        /// </summary>
        public virtual string FullCode { get; set; }

        /// <summary>
        /// TODO: Add description...
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// TODO: Add description...
        /// </summary>
        public virtual short Level { get; set; }

        /// <summary>
        /// TODO: Add description...
        /// </summary>
        public virtual string Description { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the database row for this entity. This property is auto-generated.
        /// </summary>
        public virtual Guid RowGuid { get; set; }

        /// <summary>
        /// Gets or sets the date when database row for this entity was last modified. This property is auto-generated.
        /// </summary>
        public virtual DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets the todo: add description...
        /// </summary>
        public virtual DetailAccount Parent { get; set; }

        /// <summary>
        /// Gets or sets the fiscal period in which this detail account is defined
        /// </summary>
        public virtual FiscalPeriod FiscalPeriod { get; set; }

        /// <summary>
        /// Gets or sets the branch that defines this detail account
        /// </summary>
        public virtual Branch Branch { get; set; }

        private void InitReferences()
        {
            FiscalPeriod = new FiscalPeriod();
            Branch = new Branch();
            Children = new List<DetailAccount>();
        }
    }
}
