// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.431
//     Template Version: 1.0
//     Generation Date: 2018-10-21 11:38:30 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SPPC.Tadbir.Model.Core;
using SPPC.Tadbir.Model.Corporate;

namespace SPPC.Tadbir.Model.Finance
{
    /// <summary>
    /// سند مالی که اطلاعات پولی مرتبط با یک پیشامد مالی را در سازمان نگهداری می کند
    /// </summary>
    public partial class Voucher : OperationalEntity
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public Voucher()
        {
            No = String.Empty;
            Date = DateTime.Now;
            Reference = String.Empty;
            Description = String.Empty;
            ModifiedDate = DateTime.Now;
            InitReferences();
        }

        /// <summary>
        /// شناسه دیتابیسی وضعیت ثبتی این سند مالی
        /// </summary>
        public virtual int StatusId { get; set; }

        /// <summary>
        /// شناسه دیتابیسی مستند اداری مرتبط با این سند مالی
        /// </summary>
        public virtual int? DocumentId { get; set; }

        /// <summary>
        /// شرح سند مالی که جزئیات بیشتری را در مورد پیشامد مالی ارائه می دهد
        /// </summary>
        public virtual string Description { get; set; }

        /// <summary>
        /// مجموعه ای از آرتیکل های موجود در سند مالی
        /// </summary>
        public virtual IList<VoucherLine> Lines { get; protected set; }

        /// <summary>
        /// مستند اداری مرتبط با این سند مالی
        /// </summary>
        public virtual Document Document { get; set; }

        /// <summary>
        /// وضعیت ثبتی این سند مالی
        /// </summary>
        public virtual DocumentStatus Status { get; set; }

        private void InitReferences()
        {
            Lines = new List<VoucherLine>();
            FiscalPeriod = new FiscalPeriod();
            Branch = new Branch();
            Status = new DocumentStatus();
        }
    }
}
