// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.2.1424
//     Template Version: 1.0
//     Generation Date: 2022-08-28 10:49:05 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SPPC.Tadbir.Model.Reporting;

namespace SPPC.Tadbir.Persistence.Mapping
{
    internal static class ChartParameterMap
    {
        internal static void BuildMapping(EntityTypeBuilder<ChartParameter> builder)
        {
            builder.ToTable("ChartParameter", "Reporting");
            builder.HasKey(e => e.Id);
            builder.Property(e => e.Id)
                .HasColumnName("ChartParameterID");
            builder.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(32);
            builder.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(32);
            builder.Property(e => e.RowGuid)
                .HasColumnName("rowguid")
                .HasDefaultValueSql("(newid())");
            builder.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            builder.HasOne(e => e.Chart)
                .WithMany()
                .HasForeignKey(e => e.ChartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reporting_ChartParameter_Reporting_Chart");
        }
    }
}
