// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.2.1435
//     Template Version: 1.0
//     Generation Date: 2022-09-13 10:32:14 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SPPC.Tadbir.Model.Reporting;

namespace SPPC.Tadbir.Persistence.Mapping
{
    internal static class UsedParameterMap
    {
        internal static void BuildMapping(EntityTypeBuilder<UsedParameter> builder)
        {
            builder.ToTable("UsedParameter", "Reporting");
            builder.HasKey(e => e.Id);
            builder.Property(e => e.Id)
                .HasColumnName("UsedParameterID");
            builder.Property(e => e.RowGuid)
                .HasColumnName("rowguid")
                .HasDefaultValueSql("(newid())");
            builder.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            builder.HasOne(e => e.Parameter)
                .WithMany()
                .HasForeignKey("ParameterID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reporting_UsedParameter_Reporting_Parameter");
            builder.HasOne(e => e.Function)
                .WithMany(e => e.Parameters)
                .HasForeignKey("FunctionID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Reporting_UsedParameter_Reporting_Function");
        }
    }
}
