// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.386
//     Template Version: 1.0
//     Generation Date: 09/02/2018 09:26:41 ق.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { Environment } from "../../enviroment";

export class CostCenterApi {

    // ccenters/fp/{fpId:min(1)}/branch/{branchId:min(1)}
    public static FiscalPeriodBranchCostCenters = Environment.BaseUrl + "/ccenters/fp/{0}/branch/{1}";

    // ccenters/lookup/fp/{fpId:min(1)}/branch/{branchId:min(1)}
    public static FiscalPeriodBranchCostCentersLookup = Environment.BaseUrl + "/ccenters/lookup/fp/{0}/branch/{1}";

    // ccenters
    public static CostCenters = Environment.BaseUrl + "/ccenters";

    // ccenters/{ccenterId:min(1)}
    public static CostCenter = Environment.BaseUrl + "/ccenters/{0}";

    // ccenters/{ccenterId:min(1)}/children
    public static CostCenterChildren = Environment.BaseUrl + "/ccenters/{0}/children";

    // ccenters/metadata
    public static CostCenterMetadata = Environment.BaseUrl + "/ccenters/metadata";

    // ccenters/fullcode/{parentId}
    public static CostCenterFullCode = Environment.BaseUrl + "/ccenters/fullcode/{0}";
}