USE master;
GO

CREATE LOGIN [@LoginName]
WITH PASSWORD = '@Password',
DEFAULT_DATABASE = master,
CHECK_POLICY = OFF,
CHECK_EXPIRATION = OFF;
GO

ALTER SERVER ROLE securityadmin ADD MEMBER @LoginName;
GO

ALTER SERVER ROLE dbcreator ADD MEMBER @LoginName;
GO

ALTER SERVER ROLE sysadmin ADD MEMBER @LoginName;
GO
