//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPPC.Tadbir.Workflow
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDocumentStateBasic")]
    public interface IDocumentStateBasic
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDocumentStateBasic/DoRequest", ReplyAction = "http://tempuri.org/IDocumentStateBasic/DoRequestResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "resultCode")]
        int DoRequest(SPPC.Tadbir.Workflow.StateOperation operation);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDocumentStateBasic/DoRequest", ReplyAction = "http://tempuri.org/IDocumentStateBasic/DoRequestResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "resultCode")]
        System.Threading.Tasks.Task<int> DoRequestAsync(SPPC.Tadbir.Workflow.StateOperation operation);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentStateBasicChannel : IDocumentStateBasic, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentStateBasicClient : System.ServiceModel.ClientBase<IDocumentStateBasic>, IDocumentStateBasic
    {

        public DocumentStateBasicClient()
        {
        }

        public DocumentStateBasicClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public DocumentStateBasicClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DocumentStateBasicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DocumentStateBasicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public int DoRequest(SPPC.Tadbir.Workflow.StateOperation operation)
        {
            return base.Channel.DoRequest(operation);
        }

        public System.Threading.Tasks.Task<int> DoRequestAsync(SPPC.Tadbir.Workflow.StateOperation operation)
        {
            return base.Channel.DoRequestAsync(operation);
        }
    }
}
