[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.ManageCartableActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.GetTransactionSummaryActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "SPPC.Tadbir.Workflow.MoveCartableItemActivity.#Execute(System.Activities.CodeActivityContext)", Justification = "Parameter is validated using Verify utility class.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#Prepare(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#Review(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#RejectReviewed(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#Confirm(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionDecisionWorkflow.#Approve(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#Prepare(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#Review(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#RejectReviewed(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#Confirm(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionTimeoutWorkflow.#Approve(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#Prepare(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#Review(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#RejectReviewed(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#Confirm(System.Int32,System.String)", Justification = "Object is disposed only once.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "SPPC.Tadbir.Workflow.TransactionWorkflow.#Approve(System.Int32,System.String)", Justification = "Object is disposed only once.")]

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

