// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.858
//     Template Version: 1.0
//     Generation Date: 4/8/2020 6:16:32 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


export interface AccountOwner {
    accountId: number;
    id: number;
    bankName: string;
    accountType: number;
    bankBranchName: string;
    branchIndex: string;
    accountNumber: string;
    cardNumber: string;
    shabaNumber: string;
    description?: string;
}
