// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.712
//     Template Version: 1.0
//     Generation Date: 9/16/2019 8:55:11 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


export interface Currency {
    branchId: number;
    branchName: string;
    minorUnitKey: string;
    id: number;
    branchScope: number;
    name: string;
    country: string;
    code: string;
    taxCode: number;
    minorUnit: string;
    multiplier: number;
    decimalCount: number;
    isActive: boolean;
    description?: string;
    isDefaultCurrency: boolean;
}
