// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 2017-04-17 10:52:19 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SPPC.Tadbir.Model.Corporate;
using SwForAll.Platform.Domain;

namespace SPPC.Tadbir.Model.Finance
{
    /// <summary>
    /// Represents a single entry (article) in a financial transaction
    /// </summary>
    public partial class TransactionLine : IEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionLine"/> class.
        /// </summary>
        public TransactionLine()
        {
            this.Description = String.Empty;
            this.ModifiedDate = DateTime.Now;
            InitReferences();
        }

        /// <summary>
        /// Gets or sets the unique identifier for this entity. This property is auto-generated.
        /// </summary>
        public virtual int Id { get; set; }

        /// <summary>
        /// Gets or sets the detail information that further describes this financial entry (article)
        /// </summary>
        public virtual string Description { get; set; }

        /// <summary>
        /// Gets or sets the amount debited in this financial transaction entry
        /// </summary>
        public virtual decimal Debit { get; set; }

        /// <summary>
        /// Gets or sets the amount credited in this financial transaction entry
        /// </summary>
        public virtual decimal Credit { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the database row for this entity. This property is auto-generated.
        /// </summary>
        public virtual Guid RowGuid { get; set; }

        /// <summary>
        /// Gets or sets the date when database row for this entity was last modified. This property is auto-generated.
        /// </summary>
        public virtual DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets the financial transaction in which this entry is defined
        /// </summary>
        public virtual Transaction Transaction { get; set; }

        /// <summary>
        /// Gets or sets the financial account affected by this transaction entry
        /// </summary>
        public virtual Account Account { get; set; }

        /// <summary>
        /// Gets or sets the currency used in this financial transaction entry
        /// </summary>
        public virtual Currency Currency { get; set; }

        /// <summary>
        /// Gets or sets the branch for which this financial article is defined
        /// </summary>
        public virtual Branch Branch { get; set; }

        /// <summary>
        /// Gets or sets the fiscal period that defines business scope for this financial article
        /// </summary>
        public virtual FiscalPeriod FiscalPeriod { get; set; }

        private void InitReferences()
        {
            Transaction = new Transaction();
            Account = new Account();
            Currency = new Currency();
            Branch = new Branch();
            FiscalPeriod = new FiscalPeriod();
        }
    }
}
