// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 4/30/2020 3:48:03 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace SPPC.Tadbir.Model.Metadata
{
    /// <summary>
    /// اطلاعات یکی از شهرهای یک استان را نگهداری می کند
    /// </summary>
    public partial class City : CoreEntity
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public City()
        {
            Name = String.Empty;
            Code = String.Empty;
            ModifiedDate = DateTime.Now;
        }

        /// <summary>
        /// نام شهر
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// کد شهر
        /// </summary>
        public virtual string Code { get; set; }

        /// <summary>
        /// استان مربوط به این شهر
        /// </summary>
        public virtual Province Province { get; set; }
    }
}
