export var ViewName;
(function (ViewName) {
    ViewName[ViewName["Account"] = 1] = "Account";
    ViewName[ViewName["Voucher"] = 2] = "Voucher";
    ViewName[ViewName["VoucherLine"] = 3] = "VoucherLine";
    ViewName[ViewName["User"] = 4] = "User";
    ViewName[ViewName["Role"] = 5] = "Role";
    ViewName[ViewName["DetailAccount"] = 6] = "DetailAccount";
    ViewName[ViewName["CostCenter"] = 7] = "CostCenter";
    ViewName[ViewName["Project"] = 8] = "Project";
    ViewName[ViewName["FiscalPeriod"] = 9] = "FiscalPeriod";
    ViewName[ViewName["Branch"] = 10] = "Branch";
    ViewName[ViewName["Company"] = 11] = "Company";
    ViewName[ViewName["AccountGroup"] = 12] = "AccountGroup";
    ViewName[ViewName["OperationLog"] = 13] = "OperationLog";
    ViewName[ViewName["AccountCollection"] = 14] = "AccountCollection";
    ViewName[ViewName["JournalByDateByRow"] = 15] = "JournalByDateByRow";
    ViewName[ViewName["JournalByDateByRowDetail"] = 16] = "JournalByDateByRowDetail";
    ViewName[ViewName["JournalByDateByLedger"] = 17] = "JournalByDateByLedger";
    ViewName[ViewName["JournalByDateBySubsidiary"] = 18] = "JournalByDateBySubsidiary";
    ViewName[ViewName["JournalByDateSummary"] = 19] = "JournalByDateSummary";
    ViewName[ViewName["JournalByDateSummaryByDate"] = 20] = "JournalByDateSummaryByDate";
    ViewName[ViewName["JournalByDateSummaryByMonth"] = 21] = "JournalByDateSummaryByMonth";
    ViewName[ViewName["JournalByNoByRow"] = 22] = "JournalByNoByRow";
    ViewName[ViewName["JournalByNoByRowDetail"] = 23] = "JournalByNoByRowDetail";
    ViewName[ViewName["JournalByNoByLedger"] = 24] = "JournalByNoByLedger";
    ViewName[ViewName["JournalByNoBySubsidiary"] = 25] = "JournalByNoBySubsidiary";
    ViewName[ViewName["JournalByNoSummary"] = 26] = "JournalByNoSummary";
    ViewName[ViewName["AccountBookSingle"] = 27] = "AccountBookSingle";
    ViewName[ViewName["AccountBookSingleSummary"] = 28] = "AccountBookSingleSummary";
    ViewName[ViewName["AccountBookSummary"] = 29] = "AccountBookSummary";
})(ViewName || (ViewName = {}));
//# sourceMappingURL=viewName.js.map