// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.646
//     Template Version: 1.0
//     Generation Date: 04/15/1398 03:40:55 ب.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

export const SecureEntity = {
    Account: 'Account',
    DetailAccount: 'DetailAccount',
    CostCenter: 'CostCenter',
    Project: 'Project',
    AccountGroup: 'AccountGroup',
    AccountCollection: 'AccountCollection',
    AccountRelations: 'AccountRelations',
    Currency: 'Currency',
    FiscalPeriod: 'FiscalPeriod',
    Branch: 'Branch',
    Voucher: 'Voucher',
    User: 'User',
    Role: 'Role',
    Company: 'Company',
    RowAccess: 'RowAccess',
    Setting: 'Setting',
    OperationLog: 'OperationLog',
    UserReport: 'UserReport',
    Journal: 'Journal',
    AccountBook: 'AccountBook',
    Report: 'Report'
}