import { TestBalanceApi } from "@sppc/finance/service/api/testBalanceApi";


export enum ViewName {
  Account = 1,
  Voucher = 2,
  VoucherLine = 3,
  User = 4,
  Role = 5,
  DetailAccount = 6,
  CostCenter = 7,
  Project = 8,
  FiscalPeriod = 9,
  Branch = 10,
  Company = 11,
  AccountGroup = 12,
  OperationLog = 13,
  AccountCollection = 14,
  JournalByDateByRow = 15,
  JournalByDateByRowDetail = 16,
  JournalByDateByLedger = 17,
  JournalByDateBySubsidiary = 18,
  JournalByDateSummary = 19,
  JournalByDateSummaryByDate = 20,
  JournalByDateSummaryByMonth = 21,
  JournalByNoByRow = 22,
  JournalByNoByRowDetail = 23,
  JournalByNoByLedger = 24,
  JournalByNoBySubsidiary = 25,
  JournalByNoSummary = 26,
  AccountBookSingle = 27,
  AccountBookSingleSummary = 28,
  AccountBookSummary = 29,
  Currency = 30,
  CurrencyRate = 31,
  TestBalance2Column = 32,
  TestBalance4Column = 33,
  TestBalance6Column = 34,
  TestBalance8Column = 35,
  TestBalance10Column = 36,
  CurrencyBook = 37,
  CurrencyBookSingle = 38,
  CurrencyBookSingleSummary = 39,
  CurrencyBookSummary = 40,
  NumberList = 41,
  VoucherLineDetail = 42,
  BalanceByAccount = 58
}
