// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.2.1424
//     Template Version: 1.0
//     Generation Date: 2022-08-28 10:05:47 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using SPPC.Framework.Values;

namespace SPPC.Tadbir.ViewModel.Reporting
{
    /// <summary>
    /// اطلاعات یکی از نمودارهای کاربری در داشبورد را نگهداری می کند
    /// </summary>
    public partial class ChartViewModel : ViewModelBase
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public ChartViewModel()
        {
            Title = String.Empty;
            Type = String.Empty;
            Function = String.Empty;
            Setting = String.Empty;
            DefaultSetting = String.Empty;
            Description = String.Empty;
        }

        /// <summary>
        /// شناسه دیتابیسی این موجودیت که به صورت خودکار توسط دیتابیس تولید می شود
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// عنوان چندزبانه که عملکرد نمودار را به اختصار برای کاربر توضیح می دهد
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(128, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Title { get; set; }

        /// <summary>
        /// نوع نمایشی نمودار، مانند نمودار ستونی، نمودار میله ای، نمودار خطی و غیره
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Type { get; set; }

        /// <summary>
        /// تابع محاسباتی مورد استفاده در نمودار، مانند گردش بدهکار، گردش بستانکار، مانده و غیره
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Function { get; set; }

        /// <summary>
        /// تنظیمات جاری نمودار که در قالب مرسوم جی سان نگهداری می شود
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(1024, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Setting { get; set; }

        /// <summary>
        /// تنظیمات پیش فرض نمودار که در قالب مرسوم جی سان نگهداری می شود
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(1024, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string DefaultSetting { get; set; }

        /// <summary>
        /// شرح اختیاری که برای توضیح دقیقتر عملکرد نمودار قابل استفاده است
        /// </summary>
        [StringLength(512, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Description { get; set; }
    }
}
