// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.292
//     Template Version: 1.0
//     Generation Date: 2018-05-15 5:47:43 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

export interface Command {
    permissionId?: number;
    children: Array<Command>;
    id: number;
    title: string;
    routeUrl : string;
}
