// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.776
//     Template Version: 1.0
//     Generation Date: 09/30/1398 12:25:16 ب.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SPPC.Tadbir.Model.Core;

namespace SPPC.Tadbir.Persistence.Mapping
{
    internal static class SysOperationLogMap
    {
        internal static void BuildMapping(EntityTypeBuilder<SysOperationLog> builder)
        {
            builder.ToTable("SysOperationLog", "Core");
            builder.HasKey(e => e.Id);
            builder.Property(e => e.Id)
                .HasColumnName("SysOperationLogID");
            builder.Property(e => e.Date)
                .IsRequired();
            builder.Property(e => e.Time)
                .IsRequired();
            builder.Property(e => e.EntityId);
            builder.Property(e => e.Description);
            builder.Property(e => e.RowGuid)
                .HasColumnName("rowguid")
                .HasDefaultValueSql("(newid())");
            builder.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            builder.HasOne(e => e.Operation)
                .WithMany()
                .HasForeignKey("OperationID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Core_SysOperationLog_Metadata_Operation");
            builder.HasOne(e => e.Source)
                .WithMany()
                .HasForeignKey("SourceID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Core_SysOperationLog_Metadata_Source");
            builder.HasOne(e => e.EntityType)
                .WithMany()
                .HasForeignKey("EntityTypeID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Core_SysOperationLog_Metadata_EntityType");
            builder.HasOne(e => e.SourceList)
                .WithMany()
                .HasForeignKey("SourceListID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Core_SysOperationLog_Metadata_SourceList");
            builder.HasOne(e => e.User)
                .WithMany()
                .HasForeignKey("UserID")
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Core_SysOperationLog_Auth_User");
        }
    }
}
