version: '3.4'

services:
  sppc.tadbir.web.api:
    image: ${DOCKER_REGISTRY-}sppctadbirwebapi
    build:
      context: .
      dockerfile: SPPC.Tadbir.Web.Api/Dockerfile
    ports: 
      -"8080:8080"
  
  ms-sql-server:
    image: install-restore-and-sanitize-backup-sql
    ports:
      -"1143:1143"
  
  node:
    image: nodejs
    ports:
      -"3333:5555"