version: '3.4'

volumes:
 productdata:
 
networks:
 frontend:
 backend:

services:

 sppcTadbirDB:
  ports: 
    - 14433:1433

 sppc.tadbir.web.api:
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_URLS=http://+:80
  ports:
   - 3000:80
  
 loadBalancer:
  profiles:
   - donotstart

 sppcTadbirWebNew: