version: '3.4'

volumes:
 productdata:
 
networks:
 frontend:
 backend:

services:

 sppcTadbirDB:
  image: msn1368/sppctadbirdb:dev
  user: root
  build:
   context: ../../res
   dockerfile: Dockerfile
  networks:
   - backend
  volumes:
   - productdata:/var/opt/mssql/data
   
 sppc.tadbir.web.api:
  image: msn1368/sppctadbirwebapi:latest
  build:
   context: .
   dockerfile: sppc.tadbir.web.api/Dockerfile
  depends_on:
   - sppcTadbirDB
  networks:
   - backend
   - frontend

 loadBalancer:
  image: dockercloud/haproxy:1.2.1
  depends_on:
   - sppc.tadbir.web.api
  ports:
   - 3000:80
   - 1936:1936
  links:
   - sppc.tadbir.web.api
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
  networks:
   - frontend

 sppcTadbirWebNew:
  image: msn1368/sppctadbirwebnew:dev
  build:
   context: ./SPPC.Tadbir.Web.New/ClientApp
   dockerfile: Dockerfile
  networks:
   - frontend
  ports:
   - 3003:4200

 sppcLicensingLocalWeb:
  image: msn1368/sppclicensinglocalweb:dev
  build:
   context: .
   dockerfile: sppc.tadbir.web.api/Dockerfile
  volumes:
   - productdata:/app/wwwroot
  network_mode: host

