import { Component, OnInit, AfterViewInit, Input, ViewChild, Host } from "@angular/core";
import { GridComponent, ColumnComponent } from "@progress/kendo-angular-grid";
import { ViewIdentifierComponent } from "./view-identifier.component";
import { SortDescriptor } from "@progress/kendo-data-query";
import { FilterExpression } from "../../class/filterExpression";
import { QuickReportColumnInfo, QuickReportViewInfo, ReportingService } from "../../service/report/reporting.service";
import { ReportApi } from "../../service/api/reportApi";
import { ReportManagementComponent } from "../reportManagement/reportManagement.component";
import { AutoGeneratedGridComponent } from "../../class/autoGeneratedGrid.component";
import { TreeItem } from "@progress/kendo-angular-treeview";
import { String } from '../../class/source';

@Component({
    selector: 'report-mg',
    templateUrl: `./report.mg.component.html`,
    styleUrls: [`./report.mg.component.css`],
    providers:[AutoGeneratedGridComponent]
  })

export class ReportMGComponent implements OnInit, AfterViewInit {
    
    
    

    @ViewChild(ReportManagementComponent) reportManager: ReportManagementComponent;
    

    constructor(public reportingService:ReportingService,
      @Host() public masterComponent:AutoGeneratedGridComponent) { }
  
    ngOnInit() {
      
    }    

    
  
    ngAfterViewInit(): void {
      
    }
  
   
  }