// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.1049
//     Template Version: 1.0
//     Generation Date: 2020-12-29 6:27:58 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SPPC.Tadbir.Model.Metadata
{
    /// <summary>
    /// اطلاعات فراداده ای یکی از فرم های گزارشی قابل سفارشی سازی را نگهداری می کند
    /// </summary>
    public partial class CustomForm : CoreEntity
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public CustomForm()
        {
            Name = String.Empty;
            Description = String.Empty;
            ModifiedDate = DateTime.Now;
        }

        /// <summary>
        /// کلید متن چندزبانه برای نام فرم گزارشی
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// شرح تکمیلی برای اطلاعات فراداده ای
        /// </summary>
        public virtual string Description { get; set; }
    }
}
