// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.485
//     Template Version: 1.0
//     Generation Date: 2019-01-09 4:18:30 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SPPC.Framework.Domain;
using SPPC.Tadbir.Model.Metadata;

namespace SPPC.Tadbir.Model.Reporting
{
    /// <summary>
    /// اطلاعات الگوی محلی شده یکی از گزارش های برنامه را نگهداری می کند
    /// </summary>
    public partial class LocalReport : IEntity
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public LocalReport()
        {
            Caption = String.Empty;
            Template = String.Empty;
            ModifiedDate = DateTime.Now;
            InitReferences();
        }

        /// <summary>
        /// شناسه دیتابیسی این موجودیت که به صورت خودکار توسط دیتابیس تولید می شود
        /// </summary>
        public virtual int Id { get; set; }

        /// <summary>
        /// عنوان محلی شده گزارش به صورتی که در نمای درختی گزارشات دیده می شود
        /// </summary>
        public virtual string Caption { get; set; }

        /// <summary>
        /// اطلاعات الگوی گزارش با متن های محلی شده
        /// </summary>
        public virtual string Template { get; set; }

        /// <summary>
        /// شناسه یکتای ردیف دیتابیسی که به صورت خودکار توسط دیتابیس مقداردهی می شود
        /// </summary>
        public virtual Guid RowGuid { get; set; }

        /// <summary>
        /// تاریخ آخرین تغییر رکورد دیتابیس که به صورت خودکار توسط ابزار دسترسی به داده مقداردهی می شود
        /// </summary>
        public virtual DateTime ModifiedDate { get; set; }

        /// <summary>
        /// زبان مورد استفاده در گزارش محلی شده
        /// </summary>
        public virtual Locale Locale { get; set; }

        /// <summary>
        /// گزارش سیستمی یا ذخیره شده مرجع برای این گزارش محلی شده
        /// </summary>
        public virtual Report Report { get; set; }

        private void InitReferences()
        {
            Locale = new Locale();
            Report = new Report();
        }
    }
}
