// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.631
//     Template Version: 1.0
//     Generation Date: 03/29/1398 01:04:04 ب.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { environment } from "../../../environments/environment";

export class DetailAccountApi {

    // faccounts
    public static EnvironmentDetailAccounts = environment.BaseUrl + "/faccounts";

    // faccounts/lookup
    public static EnvironmentDetailAccountsLookup = environment.BaseUrl + "/faccounts/lookup";

    // faccounts/ledger
    public static EnvironmentDetailAccountsLedger = environment.BaseUrl + "/faccounts/ledger";

    // faccounts/{faccountId:min(1)}
    public static DetailAccount = environment.BaseUrl + "/faccounts/{0}";

    // faccounts/{faccountId:min(1)}/previous
    public static PreviousEnvironmentDetailAccount = environment.BaseUrl + "/faccounts/{0}/previous";

    // faccounts/{faccountId:min(1)}/next
    public static NextEnvironmentDetailAccount = environment.BaseUrl + "/faccounts/{0}/next";

    // faccounts/{faccountId:min(1)}/children
    public static DetailAccountChildren = environment.BaseUrl + "/faccounts/{0}/children";

    // faccounts/{faccountId:int}/children/new
    public static EnvironmentNewChildDetailAccount = environment.BaseUrl + "/faccounts/{0}/children/new";

    // faccounts/fullcode/{parentId}
    public static DetailAccountFullCode = environment.BaseUrl + "/faccounts/fullcode/{0}";
}