// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SPPC.Tools.Transforms.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SPPC.Tools.Utility;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StarterCrudController : StarterCrudControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using SPPC.Tadbir.Api;
using SPPC.Tadbir.Persistence;
using SPPC.Tadbir.Resources;
using SPPC.Tadbir.Security;
using SPPC.Tadbir.Service;
using SPPC.Tadbir.ViewModel.");
            
            #line 17 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityArea));
            
            #line default
            #line hidden
            this.Write(";\r\nusing SPPC.Tadbir.Web.Api.Extensions;\r\nusing SPPC.Tadbir.Web.Api.Filters;\r\n\r\n");
            
            #line 21 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"

var plural = _model.EntityName.ToPlural();
var name = String.Format("{0}Controller", plural);

            
            #line default
            #line hidden
            this.Write("namespace SPPC.Tadbir.Web.Api.Controllers\r\n{\r\n    /// <summary>\r\n    /// عملیات س" +
                    "رویس وب برای مدیریت اطلاعات ");
            
            #line 28 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPluralPersianName));
            
            #line default
            #line hidden
            this.Write(" را پیاده سازی می کند\r\n    /// </summary>\r\n    [Produces(\"application/json\")]\r\n  " +
                    "  public class ");
            
            #line 31 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write(" : ValidatingController<");
            
            #line 31 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("ViewModel>\r\n    {\r\n        /// <summary>\r\n        /// نمونه جدیدی از این کلاس می " +
                    "سازد\r\n        /// </summary>\r\n        /// <param name=\"repository\">امکان ذخیره و" +
                    " بازیابی اطلاعات ");
            
            #line 36 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPluralPersianName));
            
            #line default
            #line hidden
            this.Write(" در دیتابیس را فراهم می کند</param>\r\n        /// <param name=\"strings\">امکان خوان" +
                    "دن متن های چندزبانه را فراهم می کند</param>\r\n        /// <param name=\"tokenServi" +
                    "ce\">امکان کار با توکن امنیتی برنامه را فراهم می کند</param>\r\n        public ");
            
            #line 39 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name));
            
            #line default
            #line hidden
            this.Write("(I");
            
            #line 39 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Repository repository, IStringLocalizer<AppStrings> strings,
            ITokenService tokenService)
            : base(strings, tokenService)
        {
            _repository = repository;
        }

        /// <summary>
        /// کلید متنی چندزبانه برای موجودیت ");
            
            #line 47 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n        protected override string EntityNameKey\r\n      " +
                    "  {\r\n            get { return AppStrings.");
            
            #line 51 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("; }\r\n        }\r\n\r\n        /// <summary>\r\n        /// به روش آسنکرون، اطلاعات صفحه" +
                    " بندی شده ");
            
            #line 55 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPluralPersianName));
            
            #line default
            #line hidden
            this.Write(" را خوانده و برمی گرداند\r\n        /// </summary>\r\n        /// <returns>اطلاعات صف" +
                    "حه بندی شده ");
            
            #line 57 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPluralPersianName));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n        // GET: api/");
            
            #line 58 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpGet]\r\n        [Route(");
            
            #line 60 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Api.");
            
            #line 60 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.IsFiscalEntity ? "Environment" : String.Empty));
            
            #line default
            #line hidden
            
            #line 60 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural));
            
            #line default
            #line hidden
            this.Write("Url)]\r\n        [AuthorizeRequest(SecureEntity.");
            
            #line 61 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(", (int)");
            
            #line 61 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Permissions.View)]\r\n        public async Task<IActionResult> Get");
            
            #line 62 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.IsFiscalEntity ? "Environment" : String.Empty));
            
            #line default
            #line hidden
            
            #line 62 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural));
            
            #line default
            #line hidden
            this.Write("Async()\r\n        {\r\n            var ");
            
            #line 64 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = await _repository.Get");
            
            #line 64 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural));
            
            #line default
            #line hidden
            this.Write("Async(GridOptions);\r\n            return JsonListResult(");
            
            #line 65 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        /// <summary>\r\n        /// به روش آسنکرون، اطلاعات نمایش" +
                    "ی ");
            
            #line 69 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" مشخص شده با شناسه دیتابیسی را خوانده و برمی گرداند\r\n        /// </summary>\r\n    " +
                    "    /// <param name=\"");
            
            #line 71 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id\">شناسه دیتابیسی ");
            
            #line 71 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" مورد نظر</param>\r\n        /// <returns>اطلاعات نمایشی ");
            
            #line 72 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" مورد نظر</returns>\r\n        // GET: api/");
            
            #line 73 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{");
            
            #line 73 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id:min(1)}\r\n        [HttpGet]\r\n        [Route(");
            
            #line 75 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Api.");
            
            #line 75 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Url)]\r\n        [AuthorizeRequest(SecureEntity.");
            
            #line 76 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(", (int)");
            
            #line 76 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Permissions.View)]\r\n        public async Task<IActionResult> Get");
            
            #line 77 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(int ");
            
            #line 77 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id)\r\n        {\r\n            var ");
            
            #line 79 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = await _repository.Get");
            
            #line 79 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 79 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id);\r\n            return JsonReadResult(");
            
            #line 80 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        /// <summary>\r\n        /// به روش آسنکرون، اطلاعات نمایش" +
                    "ی یک ");
            
            #line 84 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" جدید را پس از اعتبارسنجی در دیتابیس ذخیره می کند\r\n        /// </summary>\r\n      " +
                    "  /// <param name=\"");
            
            #line 86 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\">اطلاعات نمایشی ");
            
            #line 86 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" جدید</param>\r\n        /// <returns>اطلاعات نمایشی ذخیره شده برای ");
            
            #line 87 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n        // POST: api/");
            
            #line 88 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write("\r\n        [HttpPost]\r\n        [Route(");
            
            #line 90 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Api.");
            
            #line 90 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.IsFiscalEntity ? "Environment" : String.Empty));
            
            #line default
            #line hidden
            
            #line 90 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural));
            
            #line default
            #line hidden
            this.Write("Url)]\r\n        [AuthorizeRequest(SecureEntity.");
            
            #line 91 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(", (int)");
            
            #line 91 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Permissions.Create)]\r\n        public async Task<IActionResult> PostNew");
            
            #line 92 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async([FromBody] ");
            
            #line 92 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 92 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var result = BasicValidationResult(");
            
            #line 94 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n            if (result is BadRequestObjectResult)\r\n            {\r\n           " +
                    "     return result;\r\n            }\r\n\r\n            var outputItem = await _reposi" +
                    "tory.Save");
            
            #line 100 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 100 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return StatusCode(StatusCodes.Status201Created, outputItem);\r\n   " +
                    "     }\r\n\r\n        /// <summary>\r\n        /// به روش آسنکرون، اطلاعات نمایشی اصلا" +
                    "ح شده برای یک ");
            
            #line 105 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" موجود را پس از اعتبارسنجی در دیتابیس ذخیره می کند\r\n        /// </summary>\r\n     " +
                    "   /// <param name=\"");
            
            #line 107 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id\">شناسه دیتابیسی ");
            
            #line 107 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" اصلاح شده</param>\r\n        /// <param name=\"");
            
            #line 108 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("\">اطلاعات نمایشی اصلاح شده برای ");
            
            #line 108 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write("</param>\r\n        /// <returns>اطلاعات نمایشی ذخیره شده برای ");
            
            #line 109 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write("</returns>\r\n        // PUT: api/");
            
            #line 110 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{");
            
            #line 110 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id:min(1)}\r\n        [HttpPut]\r\n        [Route(");
            
            #line 112 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Api.");
            
            #line 112 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Url)]\r\n        [AuthorizeRequest(SecureEntity.");
            
            #line 113 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(", (int)");
            
            #line 113 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Permissions.Edit)]\r\n        public async Task<IActionResult> PutModified");
            
            #line 114 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(int ");
            
            #line 114 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id, [FromBody] ");
            
            #line 114 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 114 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            var result = BasicValidationResult(");
            
            #line 116 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 116 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id);\r\n            if (result is BadRequestObjectResult)\r\n            {\r\n         " +
                    "       return result;\r\n            }\r\n\r\n            var outputItem = await _repo" +
                    "sitory.Save");
            
            #line 122 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 122 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n            return OkReadResult(outputItem);\r\n        }\r\n\r\n        /// <summa" +
                    "ry>\r\n        /// به روش آسنکرون، اطلاعات ");
            
            #line 127 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" مشخص شده با شناسه دیتابیسی را پس از اعتبارسنجی از دیتابیس حذف می کند\r\n        //" +
                    "/ </summary>\r\n        /// <param name=\"");
            
            #line 129 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id\">شناسه دیتابیسی ");
            
            #line 129 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(" مورد نظر برای حذف</param>\r\n        // DELETE: api/");
            
            #line 130 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(plural.ToLower()));
            
            #line default
            #line hidden
            this.Write("/{");
            
            #line 130 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id:min(1)}\r\n        [HttpDelete]\r\n        [Route(");
            
            #line 132 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Api.");
            
            #line 132 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Url)]\r\n        [AuthorizeRequest(SecureEntity.");
            
            #line 133 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(", (int)");
            
            #line 133 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Permissions.Delete)]\r\n        public async Task<IActionResult> DeleteExisting");
            
            #line 134 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(int ");
            
            #line 134 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id)\r\n        {\r\n            string message = await ValidateDeleteAsync(");
            
            #line 136 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id);\r\n            if (!String.IsNullOrEmpty(message))\r\n            {\r\n           " +
                    "     return BadRequestResult(message);\r\n            }\r\n\r\n            await _repo" +
                    "sitory.Delete");
            
            #line 142 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(");
            
            #line 142 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write("Id);\r\n            return StatusCode(StatusCodes.Status204NoContent);\r\n        }\r\n" +
                    "\r\n        /// <summary>\r\n        /// به روش آسنکرون، عمل حذف را برای یکی از ");
            
            #line 147 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPluralPersianName));
            
            #line default
            #line hidden
            this.Write(" اعتبارسنجی می کند\r\n        /// </summary>\r\n        /// <param name=\"item\">شناسه " +
                    "دیتابیسی ");
            
            #line 149 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityPersianName));
            
            #line default
            #line hidden
            this.Write(@" مورد نظر برای حذف</param>
        /// <returns>اگر خطای اعتبارسنجی برای حذف وجود داشته باشد، متن محلی شده خطا
        /// و در غیر این صورت رشته خالی را برمی گرداند</returns>
        protected override async Task<string> ValidateDeleteAsync(int item)
        {
            string message = String.Empty;
            var ");
            
            #line 155 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = await _repository.Get");
            
            #line 155 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Async(item);\r\n            if (");
            
            #line 156 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName.ToLower()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                message = _strings.Format(AppStrings.It" +
                    "emByIdNotFound, AppStrings.");
            
            #line 158 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write(", item.ToString());\r\n            }\r\n\r\n            return message;\r\n        }\r\n\r\n " +
                    "       private readonly I");
            
            #line 164 "D:\GitHub\babaksoft\Projects\SPPC\framework\src\TadbirNG\SPPC.Tools.Transforms\Templates\StarterCrudController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.EntityName));
            
            #line default
            #line hidden
            this.Write("Repository _repository;\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class StarterCrudControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
