// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.492
//     Template Version: 1.0
//     Generation Date: 01/19/2019 04:06:16 ب.ظ
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { environment } from "@sppc/env/environment";

export class AccountCollectionApi {

    // acccollections
    public static AccountCollections = environment.BaseUrl + "/acccollections";

    // acccollections/{collectionId:min(1)}/accounts
    public static AccountCollectionAccounts = environment.BaseUrl + "/acccollections/{0}/accounts";
}
