// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.398
//     Template Version: 1.0
//     Generation Date: 2018-09-18 5:10:19 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using SPPC.Framework.Values;

namespace SPPC.Tadbir.ViewModel.Metadata
{
    /// <summary>
    /// اطلاعات فراداده ای یک ستون در یک نمای اطلاعاتی را نگهداری می کند
    /// </summary>
    public partial class ColumnViewModel
    {
        /// <summary>
        /// نمونه جدیدی از این کلاس می سازد
        /// </summary>
        public ColumnViewModel()
        {
            Name = String.Empty;
            Type = String.Empty;
            DotNetType = String.Empty;
            StorageType = String.Empty;
            ScriptType = String.Empty;
            Expression = String.Empty;
            Settings = String.Empty;
        }

        /// <summary>
        /// شناسه دیتابیسی این موجودیت که به صورت خودکار توسط دیتابیس تولید می شود
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// نام ستون به صورت غیر محلی شده - به زبان انگلیسی
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Name { get; set; }

        /// <summary>
        /// نوع کاربردی ستون در برنامه مانند مقدار، مبلغ یا رفرنس
        /// </summary>
        [StringLength(32, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Type { get; set; }

        /// <summary>
        /// نوع داده ای مورد استفاده در دات نت
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string DotNetType { get; set; }

        /// <summary>
        /// نوع داده ای مورد استفاده در دیتابیس
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(32, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string StorageType { get; set; }

        /// <summary>
        /// نوع داده ای مورد استفاده در جاواسکریپت
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        [StringLength(32, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string ScriptType { get; set; }

        /// <summary>
        /// تعداد کاراکتر در ستون متنی - به طور پیش فرض مقدار صفر دارد و برای ستون های غیرمتنی کاربردی ندارد
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public int Length { get; set; }

        /// <summary>
        /// حداقل تعداد کاراکتر در ستون متنی - به طور پیش فرض مقدار صفر دارد و برای ستون های غیرمتنی کاربردی ندارد
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public int MinLength { get; set; }

        /// <summary>
        /// مشخص می کند که تعداد کاراکترها در یک ستون متنی ثابت است یا نه - به طور پیش فرض مقدار نادرست دارد و برای ستون های غیرمتنی کاربردی ندارد
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public bool IsFixedLength { get; set; }

        /// <summary>
        /// مشخص می کند که وارد کردن مقدار برای ستون اجباری است یا نه
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public bool IsNullable { get; set; }

        /// <summary>
        /// مشخص می کند که آیا عمل مرتب سازی بر حسب مقادیر این ستون فعال هست یا نه
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public bool AllowSorting { get; set; }

        /// <summary>
        /// مشخص می کند که آیا عمل فیلتر کردن بر حسب مقادیر این ستون فعال هست یا نه
        /// </summary>
        [Required(ErrorMessage = ValidationMessages.FieldIsRequired)]
        public bool AllowFiltering { get; set; }

        /// <summary>
        /// وضعیت نمایشی ستون در نمای لیستی که می تواند یکی از مقادیر
        /// عدم نمایش دائمی، نمایش دائمی، نمایش یا عدم نمایش را داشته باشد
        /// </summary>
        [StringLength(32, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Visibility { get; set; }

        /// <summary>
        /// ایندکس نمایشی ستون که از صفر شروع می شود
        /// </summary>
        public short DisplayIndex { get; set; }

        /// <summary>
        /// عبارت مورد نیاز برای دسترسی به ستون در عبارات فیلتر
        /// </summary>
        [StringLength(64, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Expression { get; set; }

        /// <summary>
        /// تنظیمات پیش فرض برای نمایش ستون در نمای لیستی
        /// </summary>
        [StringLength(1024, ErrorMessage = ValidationMessages.TextFieldIsTooLong)]
        public string Settings { get; set; }

        /// <summary>
        /// گروه برای فیلد ها
        /// </summary>
        public string GroupName { get; set; }

        /// <summary>
        /// اطلاعات آبجکت مورد نظر را به صورت متنی برمی گرداند
        /// </summary>
        /// <returns>اطلاعات آبجکت مورد نظر به صورت متنی</returns>
        public override string ToString()
        {
            return Name;
        }
    }
}
