# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerComposeFile: 'src/TadbirNG/docker-compose.yml'
        additionalDockerComposeFiles: 'docker-compose.override.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'build'
        #arguments: '--build-arg ACCESS_TOKEN'#'--build-arg  --build-arg ACCESS_TOKEN=$(artifactsAccessToken)'
                                            #ARTIFACTS_ENDPOINT=$(artifactsEndpoint)
- stage: Deploy
  displayName: Deploy to docker compose 
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: Default
    steps:
    - task: DockerCompose@0
      inputs:
         containerregistrytype: 'Container Registry'
         dockerComposeFile: 'src/TadbirNG/docker-compose.yml'
         additionalDockerComposeFiles: 'docker-compose.override.yml'
         action: 'Run a Docker Compose command'
         dockerComposeCommand: 'up -d  --remove-orphans'

