variables:
  PublishPath: '.\src\TadbirNG\SPPC.Tadbir.Web.Api\publish\${CI_PIPELINE_ID}'
  PublishAngularPath: '.\src\TadbirNG\SPPC.Tadbir.Web\ClientApp'
  
  NgPath: '.\node_modules\@angular\cli\bin\ng'
  IISWorkerPath: 'C:\inetpub\wwwroot\TadbirNG\TadbirNG.WebApi'
  AngularBineriesPath: 'C:\inetpub\wwwroot\TadbirNG\TadbirNG.WebNg14'

  ApplicationPoolName: TadbirNG.Api
  CICommitRefName: key_for_node_modules

resources:
- repo: self

stages:
  - stage: build
    displayName: Build 
    jobs: 
    - job: Build_angular
      displayName: Build angular
      pool:
       name: Win-TadbirDemo-Pool
      steps:
      - task: PowerShell@2
        inputs:
         targetType: 'inline'
         script: |
            # Write your PowerShell commands here.
            cd .\src\TadbirNG\SPPC.Tadbir.Web\ClientApp
            npm install
            Copy-Item ".\src\environments\environment.prod.ts"  -Destination ".\src\environments\environment.ts" -Recurse -Force
            node "$env:NgPath" build  --configuration=production --output-path=dist

    - job: Build_dotnet
      displayName: Build dotnet
      dependsOn: Build_angular
      pool:
       name: Win-TadbirDemo-Pool
      steps:
      - checkout: none
      - task: PowerShell@2
        inputs:
         targetType: 'inline'
         script: |
          dotnet restore .\src\TadbirNG\SPPC.Tadbir.Web.Api\SPPC.Tadbir.Web.Api.csproj
          dotnet build .\src\TadbirNG\SPPC.Tadbir.Web.Api\SPPC.Tadbir.Web.Api.csproj --no-restore
          dotnet publish .\src\TadbirNG\SPPC.Tadbir.Web.Api\SPPC.Tadbir.Web.Api.csproj -c Release -o "$env:PublishPath" --verbosity normal