// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 2017-08-03 7:01:06 PM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using SPPC.Tadbir.Model.Procurement;
using FluentNHibernate.Mapping;

namespace SPPC.Tadbir.NHibernate.Mapping
{
    /// <summary>
    /// Defines fluent mappings for the <see cref="RequisitionVoucher"/> entity class.
    /// </summary>
    public partial class RequisitionVoucherMap : ClassMap<RequisitionVoucher>
    {
        /// <summary>
        /// Initializes a new instance of the RequisitionVoucherMap class and specifies NHibernate mappings
        /// using Fluent NHibernate API.
        /// </summary>
        public RequisitionVoucherMap()
        {
            Schema("Procurement");
            Table("RequisitionVoucher");
            Id(x => x.Id)
                .Column("VoucherID")
                .GeneratedBy.Identity();
            Map(x => x.No)
                .Length(64)
                .Not.Nullable();
            Map(x => x.Reference)
                .Length(64)
                .Nullable();
            Map(x => x.OrderedDate)
                .Nullable();
            Map(x => x.RequiredDate)
                .Nullable();
            Map(x => x.PromisedDate)
                .Nullable();
            Map(x => x.Reason)
                .Length(256)
                .Nullable();
            Map(x => x.WarehouseComment)
                .Length(256)
                .Nullable();
            Map(x => x.IsActive)
                .Not.Nullable();
            Map(x => x.Description)
                .Length(256)
                .Nullable();
            Map(x => x.Timestamp)
                .Not.Nullable();
            Map(x => x.ModifiedDate);
            Map(x => x.RowGuid, "rowguid")
                .Generated.Insert();

            MapReferences();
        }

        private void MapReferences()
        {
            References(x => x.FiscalPeriod)
                .Column("FiscalPeriodID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Branch)
                .Column("BranchID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Requester)
                .Column("RequesterID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Receiver)
                .Column("ReceiverID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.RequesterUnit)
                .Column("RequesterUnitID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.ReceiverUnit)
                .Column("ReceiverUnitID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Warehouse)
                .Column("WarehouseID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.ServiceJob)
                .Column("ServiceJobID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.FullAccount)
                .Column("FullAccountID")
                .Cascade.None()
                .Not.LazyLoad();
            References(x => x.Document)
                .Column("DocumentID")
                .Cascade.None()
                .Not.LazyLoad();
        }
    }
}
