// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.0.0
//     Template Version: 1.0
//     Generation Date: 2017-04-17 10:52:09 AM
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SPPC.Tadbir.Model.Finance;
using SPPC.Framework.Domain;

namespace SPPC.Tadbir.Model.Corporate
{
    /// <summary>
    /// Represents a business unit that is registered as a legal entity
    /// </summary>
    public partial class Company : IEntity
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Company"/> class.
        /// </summary>
        public Company()
        {
            this.Name = String.Empty;
            this.Description = String.Empty;
            this.ModifiedDate = DateTime.Now;
            InitReferences();
        }

        /// <summary>
        /// Gets or sets the unique identifier for this entity. This property is auto-generated.
        /// </summary>
        public virtual int Id { get; set; }

        /// <summary>
        /// Gets or sets the name of this company
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// Gets or sets the detail information related to this company
        /// </summary>
        public virtual string Description { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier for the database row for this entity. This property is auto-generated.
        /// </summary>
        public virtual Guid RowGuid { get; set; }

        /// <summary>
        /// Gets or sets the date when database row for this entity was last modified. This property is auto-generated.
        /// </summary>
        public virtual DateTime ModifiedDate { get; set; }

        /// <summary>
        /// Gets or sets the collection of all physical branches controlled by this company
        /// </summary>
        public virtual IList<Branch> Branches { get; protected set; }

        /// <summary>
        /// Gets or sets the collection of all fiscal periods defined for this company
        /// </summary>
        public virtual IList<FiscalPeriod> FiscalPeriods { get; protected set; }

        /// <summary>
        /// Gets or sets the parent of this company in the main company hierarchy
        /// </summary>
        public virtual Company Parent { get; set; }

        private void InitReferences()
        {
            this.Branches = new List<Branch>();
            this.FiscalPeriods = new List<FiscalPeriod>();
            Children = new List<Company>();

            //// IMPORTANT NOTE: DO NOT add initialization statements for one-to-one and many-to-one relationships.
            //// 1. Initializing one-to-one associations causes StackOverflowException (A initializes B and B initializes A)
            //// 2. Initializing many-to-one associations causes most mapping tests to fail, because they will trigger many
            //// unnecessary operations (INSERT and UPDATE) by in-memory SQLite database.
        }
    }
}
