// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.SystemContext.Dispose")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.TadbirContext.Dispose")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.AddAccountCostCentersAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.AddAccountProjectsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.AddCostCenterAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.AddDetailAccountAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.AddProjectAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.GetConnectableDetailAccountsForAccountAsync(System.Int32,System.Boolean,SPPC.Framework.Presentation.GridOptions)~System.Threading.Tasks.Task{System.Collections.Generic.IList{SPPC.Tadbir.ViewModel.Finance.AccountItemBriefViewModel}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.RemoveAccountCostCentersAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.RemoveAccountDetailAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.RemoveAccountProjectsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.RemoveCostCenterAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.RemoveDetailAccountAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements must be ordered by access", Justification = "Suppressed in favor of more semantic source code organization", Scope = "member", Target = "~M:SPPC.Tadbir.Persistence.RelationRepository.RemoveProjectAccountsAsync(SPPC.Tadbir.ViewModel.Finance.AccountItemRelationsViewModel)~System.Threading.Tasks.Task")]