import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MessageService } from '@progress/kendo-angular-l10n';

import { SharedRoutingModule } from '@sppc/shared/shared-routing.module';

import { BrowserStorageService, DashboardService, GridMessageService, GridService, LookupService, MetaDataService, ReportingService, SppcMessageService } from '@sppc/shared/services/index';

import {
  SppcGridColumn, SppcAutoGridColumn, SppcGridReorder, SppcAutoGeneratedGridReorder, SppcAutoGeneratedGridResize, SppcGridResize, SppcCheckAccess,
  SppcViewTreeConfig
} from '@sppc/shared/directive/index';
import { GridSettingComponent } from '@sppc/shared/directive/grid/component/grid-setting.component';
import { AutoGeneratedGridSettingComponent } from '@sppc/shared/directive/grid/component/auto-generated-grid-setting.component';
import { SelectFormGridSettingComponent } from '@sppc/shared/directive/grid/component/selectForm-grid-setting.component';

import { SppcDatePipe } from '@sppc/shared/pipes/sppc.date.pipe';
import { SppcNumConfigPipe } from '@sppc/shared/pipes/sppc.numConfig.pipe';
import { ReplaceLineBreaksPipe } from '@sppc/shared/pipes/sppc.replaceLineBreaks.pipe';

import { MetaDataResolver } from '@sppc/shared/class/metadata/metadata.resolver';
import { DefaultComponent } from '@sppc/shared/class/default.component';
import { AutoGeneratedGridComponent } from '@sppc/shared/class/autoGeneratedGrid.component';
import { GridExplorerComponent } from '@sppc/shared/class/gridExplorer.component';
import { DialogComponent } from '@sppc/shared/class/dialog.component';


import { LayoutComponent } from '@sppc/shared/components/layout/layout.component';
import { DashboardComponent } from '@sppc/shared/components/dashboard/dashboard.component';
import { AppfooterComponent } from '@sppc/shared/components/appfooter/appfooter.component';
import { AppheaderComponent } from '@sppc/shared/components/appheader/appheader.component';
import { AppmenuComponent } from '@sppc/shared/components/appmenu/appmenu.component';
import { AppsettingComponent } from '@sppc/shared/components/appsetting/appsetting.component';
import { BreadCumbComponent } from '@sppc/shared/components/breadCumb/breadcrumb.component';
import { HomeComponent } from '@sppc/shared/components/home/home.component';
import { LoginComponent } from '@sppc/shared/components/login/login.component';
import { LoginCompleteComponent } from '@sppc/shared/components/login/login.complete.component';
import { LoginContainerComponent } from '@sppc/shared/components/login/login.container.component';
import { LogoutComponent } from '@sppc/shared/components/login/logout.component';
import { NavMenuComponent } from '@sppc/shared/components/navmenu/navmenu.component';
import { ReportManagementComponent } from '@sppc/shared/components/reportManagement/reportManagement.component';
import { QuickReportSettingComponent } from '@sppc/shared/components/reportManagement/QuickReport-Setting.component';
import { ReportsQueries } from '@sppc/shared/components/reportManagement/reports.queries';
import { ReportParametersComponent } from '@sppc/shared/components/reportParameters/reportParameters.component';
import { ReportViewerComponent } from '@sppc/shared/components/reportViewer/reportViewer.component';
import { ReportParamComponent } from '@sppc/shared/components/viewIdentifier/reportParam.component';
import { ViewIdentifierComponent } from '@sppc/shared/components/viewIdentifier/view-identifier.component';

@NgModule({
  imports: [
    CommonModule,
    SharedRoutingModule    
  ],

  declarations: [LayoutComponent, DashboardComponent, AppfooterComponent, AppheaderComponent, AppmenuComponent, AppsettingComponent, BreadCumbComponent, HomeComponent, LoginComponent,
    LoginCompleteComponent, LoginContainerComponent, LogoutComponent, NavMenuComponent, ReportManagementComponent, QuickReportSettingComponent, ReportsQueries, ReportParametersComponent,
    ReportViewerComponent, ReportParamComponent, ViewIdentifierComponent, SppcGridColumn, SppcAutoGridColumn, SppcGridReorder, SppcAutoGeneratedGridReorder, SppcAutoGeneratedGridResize,
    SppcGridResize, SppcCheckAccess, SppcViewTreeConfig, GridSettingComponent, AutoGeneratedGridSettingComponent, SelectFormGridSettingComponent, SppcDatePipe, SppcNumConfigPipe,
    ReplaceLineBreaksPipe, DialogComponent],

  providers: [BrowserStorageService, DashboardService, GridService, LookupService, MetaDataService, ReportingService, SppcMessageService,
    { provide: MessageService, useClass: GridMessageService },
    MetaDataResolver, DefaultComponent, AutoGeneratedGridComponent, GridExplorerComponent
  ],

  exports: [LayoutComponent, SppcGridColumn, SppcAutoGridColumn, SppcGridReorder, SppcAutoGeneratedGridReorder, SppcAutoGeneratedGridResize, SppcGridResize, SppcCheckAccess,
    SppcViewTreeConfig, GridSettingComponent, AutoGeneratedGridSettingComponent, SelectFormGridSettingComponent, SppcDatePipe, SppcNumConfigPipe, ReplaceLineBreaksPipe]
})
export class SharedModule { }
